### PR TITLE
feat: Chapter demo - running docker-compose up will create the app, p…

### PR DESCRIPTION
**Pull request by tomnoland**
…opulate the database, and start adminer

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

Running docker-compose up will create the app, populate the database, and start adminer

To run the demo:
cd chapter/docker/models/demo 
docker-compose up

Environmental variables are stored in the .env file

Adminer
localhost:8080

System		PostgreSQL
Server		db
Username	postgres
Password	password
Database	        chapter

### CODE REVIEW

**Comment by allella** [comment]
@3piecechickendinnerTB @MihirSomani @vaibhavsingh97 @tomiiide would any of you have time to review Tom's Docker changes in this PR?

**Comment by allella** [comment]
@all-contributors please add @tomnoland for infra

**Comment by vaibhavsingh97** [comment]
Sure @allella, will do 👍

**Comment by vaibhavsingh97** [comment]
Thanks a lot for this PR, and upon looking at this PR it looks good to me, but I will do a detailed review and will let you know if there any changes needed.

Also, I really like the structure you put for dockerfiles and using in docker-compose 💯 

The only question I have in my mind is why we are creating a repo name `demo`, can we name something more significant, after all, we wanted to let the developer setup chapter out of the box, without concerning about ops associated with it. IMO, having a folder will create somewhat confusion, as people might hope that this folder has already had a built app that is ready to be opened/run at a click. Let me know if I am going in the wrong direction 😅

**Comment by tomnoland** [comment]
Glad you like it. Eventually, I plan to have 3 or 4 folders with different docker configurations (demo, dev, docker_dev, standalone, production, etc) in the models directory. I’ve actually already written a lot of it. I’m rewriting some code so that everything is standardized on node 14 (which I’ve done for this PR). I’m a little unclear about naming. Are you saying that it would be good to name the demo folder something more descriptive? If so, can you give me an example? 

Also, what’s our primary goal with the docker setup? Is it the ability to have a newcomer, as simply as possible, start up everything and be able to view the app, the graphql playground, and adminer (I added that just because it’s simple and I like it). If so, we should replace the top level docker-compose.yml with the docker-compose.yml file in the docker/models/demo folder. Then, a newcomer installs docker, navigates to the chapter directory, and runs docker-compose up. 10 or 15 minutes later everything’s up and running. More coming soon.

**Comment by allella** [comment]
This isn't my stack, but here's earlier context from what I can recall or find in the meeting notes and issues.

@tomnoland the MVP production use case for Docker has been suggested for running on Heroku.  The idea is that the _owner_ of an _instance_ could certainly host their application on a different platform, and I assume using Docker or not, but for MVP the discussion was to pick something that would be easy Heroku was the suggestion in part because it has an admin interface for setting environment variables, which would work around the need for the _owner_ to be configuring .env files.

@vaibhavsingh97 and @Zeko369 have made some efforts on the Heroku side, including this [earlier screenshot](https://discord.com/channels/633401573002969128/633826607617933353/681219431640072201).

**Comment by allella** [comment]
Regarding the earlier Heroku conversation, it seems we wouldn't be using Docker for that deployment option.

[In chat](https://chat.freecodecamp.org/channel/chapter?msg=BaTTLF9DigGoNicmA), Fran said "It's gonna be hosted natively" and "It's setup so you can run everything in one dyno + db and it works like a charm locally I'll setup heroku deployments on the main repo so we can have a 'demo' version"

**Comment by ojeytonwilliams** [comment]
Same issue as https://github.com/freeCodeCamp/chapter/pull/406, sorry for the premature closing.  I'm not 100% sure what happened here.

**Pull request closed without merging**
