### PR TITLE
Created tags table-gave users table tag id-updated readme with this u…

### PR DESCRIPTION
**Pull request by PrestonElliott**
Created tags table. Updated users table to add tag id column. Updated ReadMe with this user story added.

### CODE REVIEW

**Comment by QuincyLarson** [comment]
@PrestonElliott Thanks for adding this, and for updating the readme as well.

**Comment by email2vimalraj** [comment]
Sorry for commenting after merging it. Just had a question on this. Does tags belongs to a user or event?

If event, it has to be one to many (event to tags). In that case, we’ve to create another table to maintain the relationship. Please clarify

**Comment by PrestonElliott** [comment]
@email2vimalraj  for example, the JavaScript tag is associated with a React event and JavaScript tag is also associated with a Vue.js event. This would provide the ability to filter/search events on the "JavaScript" tag and return both the React and Vue.js events. 

The tag shouldn't belong to a user, but it should enable users to search for events by tag.

**Comment by nik-john** [comment]
@all-contributors please add @PrestonElliott  to doc code

**Pull request merged**
