### PR TITLE
chore: add skip navigation button

### PR DESCRIPTION
**Pull request by Sboonny**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

ref #65

### CODE REVIEW

**Comment by Sboonny** [comment]
I can't solve the merge conflict, did I miss type a step?

image


```bash
gitpod /workspace/chapter (chore/add-skip-to-content) $ git pull https://github.com/Sboonny/chapter.git chore/add-skip-to-content
From https://github.com/Sboonny/chapter
 * branch              chore/add-skip-to-content -> FETCH_HEAD
Already up to date.
gitpod /workspace/chapter (chore/add-skip-to-content) $ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
gitpod /workspace/chapter (main) $ git merge --no-ff Sboonny-chore/add-skip-to-content
merge: Sboonny-chore/add-skip-to-content - not something we can merge
gitpod /workspace/chapter (main) $ git push origin main
Everything up-to-date
gitpod /workspace/chapter (main) $ 
```

**Comment by gikf** [comment]
These suggested commands always look to me like they are trying to merge PR branch into the `main` branch.

I'd do it this way instead:
```
git checkout main
git pull upstream main
git checkout chore/add-skip-to-content
git merge main
(solve conflict in client/package.json)
npm install --package-lock-only
git add .
git commit
```

**Comment by ojeytonwilliams** [comment]
> npm install --package-lock-only

I did not know this was possible. Given the number of locks I've updated, I really wish I had. Thanks @gikf!

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Pull request merged**
