### PR TITLE
Fixing Subscribe Issue When RSVP

### LINKED ISSUE #1993: Issues in eventPage RSVP functionality
**Describe the bug**
I found two issues while testing it #1990, they aren't related to the PR, they are in the main branch:

- session ending while hanging out for a while after press RSVP button, which is the case of this console error <s>(I have no idea how long you have to wait, but I have done it two times)</s> Edit: this is false because I have done it once, luckily in the second time I checked the console and Gitpod workspace was down which cased it to fail, so only one time that happened.

image

- if you press RSVP you will subscribe, but if you cancel the RSVP and lose the subscription, you won't subscribe when you press RSVP the next time 

steps to test it 

- press RSVP while logged out, to RSVP and login  (you will become a member and subscribe)
- cancel RSVP and log out
- press RSVP while logged out, to RSVP and login (you will become a member, but you won't subscribe)

This isn't a real issue, but confusion of what to expect when you RSVP

### PR DESCRIPTION
**Pull request by ElizabethBarco**
This is in response of: https://github.com/freeCodeCamp/chapter/issues/1993

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #1993

Add a line that makes the user subscribe when RSVP.

### CODE REVIEW

**Review by gikf — CHANGES_REQUESTED** [review]
This could be changed in the `attendEvent` resolver instead. I'm not too sure if it's needed to make it to change subscription at this point though.

**Comment by Sboonny** [comment]
Yeab, the issue doesn't exist anymore, but we can make the event join similar to what you did with chapter join.

Adding a checkbox in the model, but this is too much work currently.

image

**Comment by gikf** [comment]
You mean checkbox with something like _Send me notifications about event updates_?

**Comment by Sboonny** [comment]
Yeah, but it will be to complex because joining events is always shown, not like joining chapter

**Comment by gikf** [comment]
Hey @ElizabethBarco

Thank you for opening this pull request.

As the linked issue is no longer relevant I'm going to close this PR. Sorry for the confusion!

Thank you and happy coding.

**Pull request closed without merging**
