### PR TITLE
chore: clear duplication on login section

### PR DESCRIPTION
**Pull request by Sboonny**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Found duplication while setting the environment locally, and this is a test if I am connected to the fork correctly

### CODE REVIEW

**Review by gikf — APPROVED** [review]
LGTM :+1: 

Interesting finding, out of curiosity I looked at the history, github diffs don't really explain how duplication found it way into the file :eyes:

**Comment by Sboonny** [comment]
This is my history of what happened, but it may have human error because I haven't broken through that limitation yet. 😅 

- I have added the terminal commands, next to the old ways to `foo@bar.com` email
- Oliver changed `foo@bar.com` emails, to terminal commands.
- I have noticed them but approved the PR anyway, hoping that newcomer sees it and decided "oh that's a good start to fix" like my first PR
- it has been a month, so I decided to fix it anyway while testing my git environment locally

**Comment by gikf** [comment]
I'm looking at:
[after #1488](https://github.com/freeCodeCamp/chapter/blob/67c44ef07ba62d221e27a3d2df5b9f180fd2b6ac/CONTRIBUTING.md#running-the-application) - no duplication
[after #1496](https://github.com/freeCodeCamp/chapter/blob/2bf10d4f53fbd8e08576a115f7caf9f4196eb1d8/CONTRIBUTING.md#running-the-application) - duplication present
But the diff in #1496 - [diff](https://github.com/freeCodeCamp/chapter/pull/1496/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055) there's no duplication.

**Comment by Sboonny** [comment]
I had to open #1496 twice because it was merged while I was updating it, maybe merging it twice cased duplication to occur

**Pull request merged**
