### PR TITLE
feat: integrate Sentry

### PR DESCRIPTION
**Pull request by gikf**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Ref #1371

---

- `redactSecrets` works beautifully for Sentry as well.
- By default Sentry will include in stack `logError` and `errorToSentry` functions, for the _manually_ captured exceptions. To change this _Stack Trace Rule_ can be set in _[Project] > Settings > Issue Grouping > Stack Trace Rules_, per https://docs.sentry.io/product/data-management-settings/event-grouping/stack-trace-rules/
  - `stack.function:logError ^-app -app ^-group -group`
- Built-in Sentry scrubber might need to be turned off in _[Project] > Settings > Security & Privacy_ to not scrub already redacted data.

---

- From what I've seen in the Sentry dashboard, the files are correctly linked when throwing error, so I'm not sure if additional configuration for typescript per https://docs.sentry.io/platforms/node/typescript/ is still needed.
- Similarly I'm not sure about deeper integration like tracking transactions.
- Client integration?

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Hey, @gikf this looks great.  When I get a chance to set up Sentry (and finish QA) we can give this a whirl.

**Comment by gikf** [comment]
@ojeytonwilliams let me know once you get around to that, I'll fix the conflicts then.

**Comment by ojeytonwilliams** [comment]
Yep, will do. If I take too long and it gets too messy I'll take care of it.

**Comment by ojeytonwilliams** [comment]
> If I take too long and it gets too messy I'll take care of it.

Famous last words.

This is another I need to close as stale :(

**Pull request closed without merging**
