### PR TITLE
feat: set profile links to fit-content of its parents

### LINKED ISSUE #2055: Chapter links in user profile extends to the page width
In user `/profile` links to the admined chapters have width almost the same as page width. Which means they can be activated and clicked when mouse cursor is nowhere near the link text.

image

### PR DESCRIPTION
**Pull request by dineshigdd**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #2055

I set the maxWidth property to fit-content so that the profile links in the `userProfile.tsx` will not extend to full page width

### CODE REVIEW

**Comment by dineshigdd** [comment]
Issue #2055 is about extending the profile links to full width. I set the maxWidth property of the Flex wrapper to maxWidth ={ 'fit-content' } so that there is no extra width on links

**Comment by Sboonny** [comment]
Can edit the number in `Close #XXXXX`, to link the issue and close it automatically when the PR is merged?

image

**Comment by dineshigdd** [comment]
I add the command to close issue #2055

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @dineshigdd, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by dineshigdd** [comment]
Thank you very much for merging. This is very encouraging in my coding journey. I will continue to contribute.

**Comment by gikf** [comment]
@all-contributors would you be so nice and add @dineshigdd for code?

**Pull request merged**
