### PR TITLE
feat: optionally attend events you create

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- refactor: rename tests
- feat: give event creator a choice to rsvp or not
- fix: add creator to calendar event if they attend

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #XXXXX

### CODE REVIEW

**Review by gikf — COMMENTED** [review]
It works well :+1: 

There's one thing that'd be good to add here. When somebody RSVPs, they are joined to the chapter. Instance owner can join the event when creating it, but will not be added to the chapter.

**Comment by ojeytonwilliams** [comment]
Just to make sure I've understood correctly: an owner should join the chapter automatically if they choose to attend the event?

**Comment by gikf** [comment]
Yeah, that's what I was trying to say. Of course if they aren't part of chapter already.

**Comment by ojeytonwilliams** [comment]
Cheers, that sounds like the way to go.

**Review by gikf — APPROVED** [review]
That does it! Looks good :+1:

**Pull request merged**
