### PR TITLE
Add GitPod Notes, Improve Dev Shell / WSL Notes in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by allella**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

The CONTRIBUTING.md had been tweaked in the Windows / WSL terminal shell section.

GitPod has been added as an option for launching a development environment. Added GitPod vs Traditional Dev Environment headings and links in the table of contents.

### CODE REVIEW

**Comment by allella** [comment]
This is easiest to view at https://github.com/allella/chapter/blob/docs/contributing-dev-shell-tweaks/CONTRIBUTING.md

**Comment by allella** [comment]
@ojeytonwilliams the GitPod notes are short, but feel free to suggest any improvements since you set up that feature.

**Review by Zeko369 — APPROVED** [review]

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by allella** [comment]
@ojeytonwilliams one question I have, since I haven't setup a GitPod account, is does it actually run the application too?  Or, is is just a cloned copy of the code?

If it actually runs the application, then I can updated the Running the Application section with a note.

**Comment by ojeytonwilliams** [comment]
It does run it, yeah.  If you click the button it'll set everything up for you (including seeding the db) and then runs `npm run both` and gives you a preview of the running app.

**Pull request merged**
