### PR TITLE
refactor: show loading indicators correct on event page

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Mostly a refactor, but it might help with the flakiness of the cancelling RSVP test.

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Review by gikf — APPROVED** [review]
LGTM :+1: 

Edit: welp

**Comment by ojeytonwilliams** [comment]
Hah, sorry @gikf, I didn't think this one was interesting enough to require another review so I just merged it!

**Comment by gikf** [comment]
It's not that :laughing:, I noticed it was already reviewed only after submitting my review.

**Pull request merged**
