### PR TITLE
Added margin bottom for buttons on EventForm

### PR DESCRIPTION
**Pull request by sirasitxp**
[X] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
[X] My pull request has a descriptive title (not a vague title like `Update README.md`).
[X] My pull request targets the `main` branch of Chapter.

https://github.com/freeCodeCamp/chapter/issues/1273

Ps. This is my first time making pull request for this project, so feel free to mention anything I should or shouldn't do.

### CODE REVIEW

**Comment by Sboonny** [comment]
hi @hisnameispum, I wonder what are the extra files for?

**Comment by hisnameispum** [comment]
@Sboonny Maybe it happened when I created and deleted files. Does it have any effects on the codebase?

**Comment by Sboonny** [comment]
There are empty, and I don't think there will be something that try to use them. 

I will delete them, because it doesn't seem like you intended to push them, then I will merge the pr

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @hisnameispum, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by hisnameispum** [comment]
@Sboonny Thank you very much! Really appreciate your help! Looking forward to contribute more.

**Comment by Sboonny** [comment]
@all-contributors please add @hisnameispum for Design

**Pull request merged**
