### PR TITLE
fix: Add space between event image and header using PageLayout

### LINKED ISSUE #2497: Space between event image and header
### Describe the bug:
On event page - `events/{id}` there's no space between image and header:
image
Some space should be added to separate the two. Also maybe separating margin might be set on the `PageLayout`, instead of individual pages.

### PR DESCRIPTION
**Pull request by randychilau**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #2497 

[Gitpod workspace snapshot](https://gitpod.io#snapshot/90b362e7-3cbd-40df-bf1d-6f52b55c8dd6)

as suggested in the bug description:

>  Also maybe separating margin might be set on the PageLayout, instead of individual pages.

Added to `<Box>` component, in PageLayout file, a margin top of 1rem spacing which in [chakra is "4"](https://chakra-ui.com/docs/styled-system/theme#spacing):

client/src/components/PageLayout/index.tsx

image

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @randychilau, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by Sboonny** [comment]
https://github.com/all-contributors please add @randychilau for code.

**Comment by gikf** [comment]
@all-contributors would you be so kind and add @randychilau for code?

**Comment by Sboonny** [comment]
@all-contributors would you be so kind and add @randychilau for code?

**Pull request merged**
