### PR TITLE
chore: upgrade node images to version 18

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by gikf** [comment]
Seems that branch protection rules will need to be updated as well.

**Comment by ojeytonwilliams** [comment]
> Seems that branch protection rules will need to be updated as well.

Good point, thanks.  It magically merged as soon I changed it. The other PRs, not so much...

**Comment by ojeytonwilliams** [comment]
@gikf don't worry about updating them just to pass these checks.  I'll take care of any that are ready to be merged.

**Pull request merged**
