### PR TITLE
feat: remove misused headings in chapterPage

### PR DESCRIPTION
**Pull request by Sboonny**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Remove misused Heading, I have added in chapterPage

### CODE REVIEW

**Comment by Sboonny** [comment]
Should I add [96761be](https://github.com/freeCodeCamp/chapter/pull/1987/commits/96761be8d1c70a4f548d54a08543b4f757f03d9e) to its own PR?

**Comment by ojeytonwilliams** [comment]
No need, but why inline the component?  The JSX is already quite noisy.

**Comment by Sboonny** [comment]
Reverting it 👍.

I think I have done this, because most component use inline component. at least that what I hope why I did it 😅.

**Review by ojeytonwilliams — APPROVED** [review]
Nice, LGTM :+1:

**Pull request merged**
