### PR TITLE
feat: removing iCalendar from invitations

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

The invitation email from Chapter

image

looks a lot like the invitation from Google Calendar

image

At least it does in Gmail. The reason for this is the presence of the .ics file. Gmail picks up on this and provides a helpful widget at the top.

Related: https://github.com/freeCodeCamp/chapter/issues/1670

### CODE REVIEW

**Review by gikf — COMMENTED** [review]
Any reason to still keep these?
 https://github.com/freeCodeCamp/chapter/blob/beeb7f3a9029dfc1c3b58fa3b01ee6126597b7af/server/src/controllers/Events/resolver.ts#L22

https://github.com/freeCodeCamp/chapter/blob/beeb7f3a9029dfc1c3b58fa3b01ee6126597b7af/server/src/controllers/Events/resolver.ts#L1024-L1030

**Comment by ojeytonwilliams** [comment]
Nope, they can go.

**Comment by gikf** [comment]
Then `ical-generator` dependency can be dropped too...

**Comment by ojeytonwilliams** [comment]
Cheers, @gikf. I think I've finally got everything.

**Review by gikf — APPROVED** [review]

**Pull request merged**
