### PR TITLE
Update diagram

### PR DESCRIPTION
**Pull request by matjack1**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

Following issue #54 and PR #70 I thought opening a new one since the previous one wasn't getting feedback.

This PR is following the discussions we had in the issue and PR:

 - update of the link in README to point directly to the image, so that we don't need to update the file itself anymore
 - update the diagram using [DBeaver](https://dbeaver.io/)
 - I've fixed the SQL schema so that it can be imported without changes

### CODE REVIEW

**Comment by allella** [comment]
Nice.

Only thing I noticed is since the link in the README is absolute to the upstream Chapter repo it will also show that image in anybody's fork.  That's probably not ideal if we can make the link relative to the repo and branch.  That may be more complex than it sounds, so I'm not going to hold this up on that question.

Squashing and merging since the existing diagram is way out of date.

**Comment by allella** [comment]
Thanks @matjack1.

One minor thing for future PRs, I believe the [CONTRIBUTING.MD](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md#step-3-making-changes-to-chapter-codebase-fire) for the project would like branches to use prefixes of

fix/, feat/, docs/

**Comment by matjack1** [comment]
thank you @allella I'll do that next time! :)

And yes, I wasn't sure how to make the diagram relative, we can try if it's necessary on future changes.

**Comment by allella** [comment]
I think we should try to make it relative because it already tripped me up. I was looking at your fork's README and seeing the out of date schema, since README was pointing to the main repo's image before that version of the file existed there.

**Comment by nik-john** [comment]
@all-contributors please add @matjack1   for doc

**Comment by nik-john** [comment]
@all-contributors please add @matjack1 for doc

**Pull request merged**
