### PR TITLE
FIX: moved Resolver test into common server/tests directory

### PR DESCRIPTION
**Pull request by paulywill**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

Looking at the current tests would suggest keeping all the tests together, i.e. `server/tests` and `client/tests`.
Although it did not take me long I had to dig around to locate the random test in  `server/controllers/Messages/resolver.test.ts`.

I realize this not moving the needle for the MVP other than agreement of placing all the tests in one location.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@paulywill what about going the other way and putting all the tests next to the files they're testing?  It has the fringe benefit that you can go from
```js
import longString from '../controllers/Messages/longString';
```
to
```js
import longString from './longString';
```

I'm fine with either direction, and I do agree that we should be consistent.

**Comment by paulywill** [comment]
Let me do some research on this.

If there's something definitive like a best practice or something to measure.

**Review by ojeytonwilliams — APPROVED** [review]
I went ahead and checked a bunch of big, popular libraries and they all used either __tests__ or tests, so I guess that will take the fewest people by surprise.

LGTM 👍

**Comment by Zeko369** [comment]
Merging to close for now, we can see what we'll do with all other tests later (i.e. cypress for client...)

**Pull request merged**
