### PR TITLE
Update database schema image

### PR DESCRIPTION
**Pull request by francocorreasosa**
Closes https://github.com/freeCodeCamp/chapter/pull/54 (till we change the schema again)

### CODE REVIEW

**Comment by allella** [comment]
@francocorreasosa I think #46 agreed to changing group(s) to chapter(s), so that may be a change on the diagram.

There was a desire to normalize the vocabulary of higher-level things in #61 and "group(s)" is pretty vague and folks liked using the core chapter(s) entity in its place.

**Comment by francocorreasosa** [comment]
@allella I could try to keep it updated as soon as changes are introduced to `master`. Maybe not with every change but periodic checks and updates should do it. 

This image was generated using dbdiagram.io (also in the image for reference), so I would expect any PR that changes the schema to have the updated image too, since the tool required to update it is free to use and available online.

**Comment by nik-john** [comment]
@francocorreasosa could you point the PR to https://github.com/nik-john/chapter instead? I was looking for the updates ER diagram anyway and have updated the SQL file so it makes sense to combine the two

**Comment by f0cus10** [comment]
At one point we should automate this image generation process. A GitHub bot maybe?

Something that will automatically issue a PR when the schema is changed. Of course, that depends on how frequent we can expect the schema to change.

**Comment by allella** [comment]
@francocorreasosa I asked on #54 if @dmmulroy could generate a new ER Diagram with one of the open-source tools he mentioned. Pinging you in case you have input on it and/or want to share the tool you used for this now outdated image.

**Comment by allella** [comment]
Well, I see dbdiagram.io in the corner, so mystery solved on that part.

**Comment by xarielx** [comment]
Should we incorporate something like a live link of the dbdiagram?
We can update this much easier.
<iframe width="560" height="315" src='https://dbdiagram.io/embed/5da9492502e6e93440f25b41'> </iframe>

**Comment by allella** [comment]
I like the idea.  @chrismgonzalez @vkWeb are there any issues with dropping iframes in Github docs?

**Comment by matjack1** [comment]
Look at this diagram:

chapter-er

Made with DBeaver: https://dbeaver.io/ which is free, open source and multiplatform, meaning that anyone can update this :)

If you like it I can set up a small guide on how to generate these (it's very quick).

**Comment by vkWeb** [comment]
> [...] are there any issues with dropping iframes in Github docs?

@allella No we can't do that. GitHub doesn't allow putting iframes in `.md` files. :( 

We can manually update it for some time as we evolve the API, after a period of time, I don't think we'll be changing the db schema so we don't necessarily need to automate it. 

Let's update the image and merge this. What do you say @francocorreasosa?

**Comment by jamesarm97** [comment]
With the events in the DB, will there be a cost or some sort of fee variable? Right now in the schem shown above there are none, or is that just a starting point? Some sort of re-occurring field and when it will end.

**Comment by wuilliam321** [comment]
We can keep the PR open, until we have a very stable diagram. No need to merge it now, what do you think. It allows us to track all the progress.

**Comment by matjack1** [comment]
I think we should settle on deciding which tool to use (I'm proposing DBeaver as it's a OSS cross/platform tool to let everyone update the picture without any account sharing need).

And then I agree with https://github.com/freeCodeCamp/chapter/issues/54#issuecomment-543926485 to link directly the https://github.com/freeCodeCamp/chapter/raw/master/data/schema.png in the README.md, so that we can simply update the picture at later stages.

If you agree I can open another PR for this? @francocorreasosa what do you think?

**Comment by allella** [comment]
I like the DBeaver image over the others I've seen, so +1 from me on it. Also, +1 for linking to the raw image URL in Readme.

**Comment by bernhard-hofmann** [comment]
The diagram is out of date now. If you could update it I'll happily merge this PR.

**Comment by matjack1** [comment]
Since this PR wasn't getting feedback I've opened a new one here: https://github.com/freeCodeCamp/chapter/pull/129

Feel free to close it if this one is updated.

**Comment by allella** [comment]
Closing this as #129 did the trick and included updating the README image path.

**Comment by allella** [comment]
@francocorreasosa I'm seeing this was a local update-schema-image branch and not a fork branch.  I suspect we can delete that branch, but I'll defer to you on it.

**Comment by francocorreasosa** [comment]
@allella Yes indeed, deleted.

**Pull request closed without merging**
