### PR TITLE
fix: add label to invite only icon

### LINKED ISSUE #1243: Unclear Icon in the Homepage
There is a lock icon as shown in the picture for events, this isn't descriptive for people who see it. Our approach for private event inductive should be changed 

image

You can add `Invite only` text next to the `<LockIcon />` in here 

https://github.com/freeCodeCamp/chapter/blob/53e35409156efb60c7a98ec1cf24ac18c4dc39d6/client/src/components/EventCard.tsx#L33-L35

---

To get set up locally, take a look at our [contribution docs](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md). And, if you'd like to discuss more, you can head on over to [Discord](https://discord.gg/QbQd7BpaaH) and say hi. Or just comment here if you prefer.

### PR DESCRIPTION
**Pull request by Nitya-Pasrija**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #1243
Have added the text "Invite Only" next to the lock icon.

image

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @Nitya-Pasrija, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by Sboonny** [comment]
I recommend creating a branch for pull request, because it will cause annoyance for you, inputting multiple git commands to clean it

**Comment by Nitya-Pasrija** [comment]
Surely, I will create branches from now on :) Thanks

**Comment by gikf** [comment]
@all-contributors, would you be so kind and add @Nitya-Pasrija for code?

**Comment by gikf** [comment]
@all-contributors please add @Nitya-Pasrija for code

**Comment by Nitya-Pasrija** [comment]
Just wanted to ask, am I supposed to check the review box for these codes and leave my comments in here?

**Comment by Sboonny** [comment]
> Just wanted to ask, am I supposed to check the review box for these codes and leave my comments in here?

about allcontributors? It shouldn't require an input.

**Comment by Nitya-Pasrija** [comment]
No no, I was talking about the code review with images part..

**Comment by Sboonny** [comment]
oh this https://github.com/freeCodeCamp/chapter/pull/1355#issuecomment-1208436192? It's a tool, to check which files are affected with the changes, it's useful when you want to see if the feature, function or ui change will affect a page that you forgot about

https://www.codesee.io/welcome

**Comment by Nitya-Pasrija** [comment]
Yep this is what I was talking about :)

**Pull request merged**
