### PR TITLE
refactor: userProfile loading

### PR DESCRIPTION
**Pull request by gikf**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

---
- Refactors a bit to use the `Loading` component.

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by Sboonny** [comment]
I have tried to mess with it, and see why when user log in, the page doesn't change

image

tested

```ts
  if (!isLoggedIn)
    return <NextError statusCode={401} title={'Log in to see this page'} />;
  if (isLoading || !data?.userProfile) return <Loading loading={isLoading} />;
  ```
  
And got empty screen. 😞
  
  
image

**Comment by gikf** [comment]
Yeah, that didn't change. I was hoping to not touch it yet :stuck_out_tongue:, but since you are bringing it up I tried to find the solution. I'm gonna commit it in a bit.

**Comment by gikf** [comment]
I've figured out two ways, one with manual refetch after the `isLoggedIn` is changed. The second is to not load profile component unless user is logged in, that's similar to the `DashboadLayout`. I've had some fun with the second one.

**Pull request merged**
