### PR TITLE
Adding a story where organizers can see participants attendance rate

### PR DESCRIPTION
**Pull request by MirzaChilman**
Adding a user story where organizers can see the attendance rate of the participants. There's a time where the seat is limited but got lots of people in waiting list. At the event day, some people doesn't come without a proper notice. This is a loss as there are some people that way more eager to join but probably got late notice of the event.

With attendance rate we can utilize it to message the participants that their attendance rate is low and the impact is that if it reach some point it will make them to not automatically accepted to get a seat on the event.

The acceptance should be manually triggered by the organizers instead of automatically by system (where if the seats is available then he/she will automatically get the seat)

### CODE REVIEW

**Comment by mblonyox** [comment]
Should we add a ticketing system like eventbrite does? So organizer can easily validate quickly the user.

**Comment by QuincyLarson** [comment]
@MirzaChilman Good idea. Ideally we'd be able to show the organizer the participant's entire rsvp/attendance history. We can incorporate this into our schema.

**Comment by MirzaChilman** [comment]
> Should we add a ticketing system like eventbrite does? So organizer can easily validate quickly the user.

I never use eventbrite so I can't say a lot about that, will take a look into that

**Comment by nik-john** [comment]
@all-contributors please add @MirzaChilman   to doc

**Pull request merged**
