### PR TITLE
Creates a combined npm run command called lint-and-test, per #525 con…

### LINKED ISSUE #524: docs(contributing) Add run lint wording and guideline
### Describe the bug:

Consider:
1. adding wording to CONTRIBUTING that suggests linting and testing prior to running the application.
2. adding a guideline regarding the merging of pull requests that must pass linting and tests.

Reference pull request #525
### Tell us about your browser and operating system:
- Browser(s) name and version: n/a
- Operating System: n/a

### PR DESCRIPTION
**Pull request by allella**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

Closes #525 
Closes #524 

@NorthDecoder I tried to push this into your open #525 PR, but I was following the wrong GH docs and it pushed as a new branch, which I've deleted.

@ojeytonwilliams and @NorthDecoder This PR includes a new _lint-and-test_ command to package.json.  Could you check that it looks good? It runs for me, but generates a lint error, which seems to be in issue with the lint tool and not the new command itself.

The proposed changes to CONTRIBUTING.md now reference running _lint-and-test_ for the Docker Mode and Manual Mode

### CODE REVIEW

**Comment by allella** [comment]
Also, I wasn't sure of the best step name / heading for the combination of linting and unit tests. I called the heading **Always Run Code Quality Tools**, but feel free to suggest a more accurate name.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Comment by allella** [comment]
@all-contributors please add @NorthDecoder for bug docs and tests

**Comment by allella** [comment]
@all-contributors add @allella for review question tool

**Pull request merged**
