### PR TITLE
Add organizer feat: required info

### PR DESCRIPTION
**Pull request by nhsz**
This feature is a must for us (https://github.com/freeCodeCampBA) as some venues ask for this.

[Eventbrite](https://www.eventbrite.com/support/articles/en_US/How_To/how-to-create-custom-questions-for-attendees) has this feature. 

Meetup gives you the chance to add a question that appears when someone completes the RSVP, but you can't make it mandatory, some people sometimes don't complete it, it's annoying and a waste of time to be messaging them, besides [sometimes it just don't work](https://www.meetup.com/Slow-and-Steady-Hikers/messages/boards/thread/50216291).

### CODE REVIEW

**Comment by f0cus10** [comment]
I would recommend creating a [new issue](https://github.com/freeCodeCamp/chapter/issues/new) instead of a blank PR for a feature request.

**Comment by vkWeb** [comment]
@nhsz Thanks for your interest in this project. 

As @f0cus10 said you should create a new issue before sending a PR. Please create a new issue, we'll discuss there :)

**Comment by nhsz** [comment]
already comment about that [here](https://github.com/freeCodeCamp/chapter/issues/1#issuecomment-541939784), do u say I should open an issue separately?

**Comment by vkWeb** [comment]
@nhsz Can you tell me what purpose does `id` solves? I ain't getting the idea of using an `id`. Maybe because I have not used meetup.com that much. 

Thanks for your patience.

**Comment by nhsz** [comment]
Yep, I'm talking about a personal id number, like your passport. Some venues ask us to send them a list of attendees before the event including this id for security reasons, they check the info when people arrive

**Comment by vkWeb** [comment]
@nhsz It should not be in MVP because venues can always ask people to show them the email we sent. 

MVP should be as minimal as possible with core features.

**Comment by nhsz** [comment]
Ok, we'll use Eventbrite then

**Pull request closed without merging**
