### PR TITLE
feat: allow calendar and event creation

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
Builds off https://github.com/freeCodeCamp/chapter/pull/1426 (which should be merged first)

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

When an owner creates a Chapter it will try to use the owner's token to create a secondary calendar attached to their Google account.

When an owner creates an Event it will try to attach an event to the Chapter's calendar.

Currently it is impossible for anyone other than the owner to create events.

## Notes for QA

The google project is still in testing mode. This means I'll need to add a gmail address to the project users if someone wants to test this out.

Also to start the auth flow (using the address registered in the project) and add your token to the db, click on the menu and click on Authenticate with Google. Once that's done, you'll be able to create calendars and events until that key expires.

To refresh, click on Authenticate with Google again.

There's more to be done after this PR, but I think there's enough to be getting along with!

### CODE REVIEW

**Review by Sboonny — COMMENTED** [review]
@ojeytonwilliams, I am getting this error
 
image

> Error: OAuth2 keys file missing
    at createOAuth2Client (/workspace/chapter/server/src/services/Google.js:83:15)
    at getGoogleAuthUrl (/workspace/chapter/server/src/services/Google.js:38:26)
    at /workspace/chapter/server/src/app.js:162:55
    at Layer.handle [as handle_request] (/workspace/chapter/node_modules/express/lib/router/layer.js:95:5)
    at next (/workspace/chapter/node_modules/express/lib/router/route.js:144:13)
    at isLoggedIn (/workspace/chapter/server/src/app.js:149:13)
    at Layer.handle [as handle_request] (/workspace/chapter/node_modules/express/lib/router/layer.js:95:5)
    at next (/workspace/chapter/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/workspace/chapter/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/workspace/chapter/node_modules/express/lib/router/layer.js:95:5)
    
 
I am wondering if this is normal, or do we need to add key in .env.example

---

There is a merge conflict here

**Review by Sboonny — APPROVED** [review]
LGTM, didn't find issues so far

**Comment by ojeytonwilliams** [comment]
Still TODO: 

- [ ] remove the code for granting and revoking access since it's all handled by the same set of tokens.

**Comment by ojeytonwilliams** [comment]
@gikf if you've got a moment to take a look, that would be awesome.  Mostly the resolvers, to be honest, I think what I've done is fine, but if anything worrying leaps out at you please let me know!

**Review by gikf — COMMENTED** [review]
It makes logical sense to me :+1: 

Few nitpick below.

**Comment by ojeytonwilliams** [comment]
Thanks for taking the time to review this @gikf. It's nicer with your suggested changes.

I slightly goofed when adding your co-authorship, but fortunately, because I got it right once and we squash PRs, it'll work!

**Review by gikf — APPROVED** [review]
:rocket:

I don't think I'm gonna find anything else right now, so feel free to merge whenever convenient.

**Comment by ojeytonwilliams** [comment]
Lovely.  Let's see what breaks!

**Pull request merged**
