### PR TITLE
Add user story: Save RSVP'd events to calendar

### PR DESCRIPTION
**Pull request by timrodz**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

I love calendars. When using any kind of event scheduling tool, I make sure I can send some form of an invitation to them!

It would be great to consider adding this feature -which would be optional- to users who desire to save these invites in their calendars (without having to type them manually).

### CODE REVIEW

**Comment by allella** [comment]
It's a feature I use all the time, so consider my vote for wanting it. Whether it's an MVP, feature or not is debatable.  This usually allows for adding a few popular calendar services.  That might be a decent amount of work to format the links for multiple services and create the interactive UI element.  Maybe there's a widget out there to make the development part easier, so it would be nice to get other opinions and ideas on implementation and if this is an MVP or not.

**Comment by timrodz** [comment]
If we only want user stories for an MVP, I'd be happy to wait it out (or label it as not to be added for the MVP).

For the hypothetical implementation, we could refer to [this tool](https://github.com/jasonleibowitz/react-add-to-calendar-hoc). See [examples](http://leibowitz.me/react-add-to-calendar-hoc/docs/).

**Comment by allella** [comment]
I don't know that I've read where the user stories in the README are for the MVP, or beyond.

Pinging @chrismgonzalez and @QuincyLarson for clarification.

**Comment by chrismgonzalez** [comment]
@allella To my knowledge the RSVP feature is just a wanted feature, I do not believe it has been defined as part of the MVP.

**Comment by allella** [comment]
@chrismgonzalez and is the README only MVP features?  If so, then where are we capturing non-MVP user stories.

**Comment by chrismgonzalez** [comment]
@allella please see issue #83 - I just created it so we don't clog up this PR thread.  I will make one for post MVP user stories, too.

**Comment by timrodz** [comment]
Sounds good folks - I'm open to anything. 😄

**Comment by chrismgonzalez** [comment]
Hello all -  I will leave this PR up until I go to bed tonight (around 10 or so central US time).  If I see no argument for keeping it in the MVP user stories, I will move it over the #84 and close this out.

**Pull request closed without merging**
