### PR TITLE
Add schema sync instructions

### PR DESCRIPTION
**Pull request by AryanJ-NYC**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

I noticed that instructions for syncing the database with the schema (something that is necessary to initially use the application) were lacking.

I went ahead and added a script plus instructions to use the script upon app standup.

### CODE REVIEW

**Comment by Zeko369** [comment]
We shouldn't be doing this, we use migrations for this purpose.
can you maybe add a timestamp of your stream where you discuss this or write why here?

**Comment by AryanJ-NYC** [comment]
Ah, you're completely right. My bad. I basically did it because I followed the README and found the Chapters table wasn't in the DB after following the instructions.

**Comment by AryanJ-NYC** [comment]
OK, yeah. I found the migrations. 🤦‍♂ 

Should we include instructions on the front README to migrate after `docker-compose up`?

**Comment by AryanJ-NYC** [comment]
OK, yeah. So the migrations aren't running programatically. Will fix.

**Pull request closed without merging**
