### PR TITLE
fix: wrap with ChakraProvider in test

### PR DESCRIPTION
**Pull request by gikf**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

---
- Should fix issues in #2520

### CODE REVIEW

**Comment by Sboonny** [comment]
Thank you so much.

just wondering, should we revert jest update #2549 🤔

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by gikf** [comment]
> Thank you so much.
> 
> just wondering, should we revert jest update #2549 thinking

No idea :thinking:

**Comment by Sboonny** [comment]
Lets leave that to Oliver 🤣 👍

**Pull request merged**
