### PR TITLE
chore: remove init script

### LINKED ISSUE #1898: It should be possible to 'initialize' live databases
Whenever we update the [db init script ](https://github.com/freeCodeCamp/chapter/blob/2a9876947cac2de46d84488c7e869201475b7187/server/prisma/init/init.ts), we can create issues for existing databases.  For example, if we add a new permission, no existing database will have it and will behave incorrectly once the application code is updated.

The init script needs to be changed so that it can replace these tables (and only these tables).

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- feat: create migration to replace init script
- chore: delete init script

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes https://github.com/freeCodeCamp/chapter/issues/1898

This is a partial solution to the issues raised in https://github.com/freeCodeCamp/chapter/issues/1910. It doesn't touch the schema, but it does make the migrations entirely responsible for setting up and migrating the database.  Prior to this PR this responsibility was shared with the init script.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Re: deployment, this migration has already been applied to the live db, so all that needs to happen is for it to be marked as such.

**Comment by gikf** [comment]
With these changes how can for example, another permission be added, to include in new migration?

**Comment by ojeytonwilliams** [comment]
We'd need to write the SQL queries ourselves, unfortunately.  For the specific example of a new permission that was owner only, it would look like this:

```sql
INSERT INTO instance_permissions (name, created_at, updated_at)
VALUES ('new-permission', NOW(), NOW());

INSERT INTO instance_role_permissions (instance_role_id, instance_permission_id, created_at, updated_at)
VALUES 
    ((SELECT id FROM instance_roles WHERE name = 'owner'),
    (SELECT id FROM instance_permissions WHERE name = 'new-permission'),
    NOW(),
    NOW());
```

It's awkward and I'd love to know of a better way.  However, it feels like this is necessary since, effectively, permission data is part of the schema.

What do you think? Does this all make sense?

**Review by gikf — APPROVED** [review]
I really don't mind, just making sure.

**Comment by ojeytonwilliams** [comment]
Okay, cool. Thanks for the review!

Let's see how this works in practice.

**Pull request merged**
