### PR TITLE
feat: adding chapter user bans

### PR DESCRIPTION
**Pull request by gikf**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

To do
- [x] I guess deleting bans too?
- [x] ~~Don't query `user_bans` in client~~
- [x] Tests
  - [x] Test
  - [x] Fully working

---
- Related to #98
- Adds UI portion for banning chapter user in the `dashboard/chapters/{id}/users`.
- Adds resolver adding ban to database.
- Nothing of the actual blocking access is tackled here.
- Uses ~~two~~ one custom `FieldResolver`s on the `ChapterUser` to handle most of the verification _who can what and when_ on server side.
  - ~~`isBanned` checks if user is among banned for the chapter. This might need changing/tuning, as it makes additional query for each user.~~
  - `canBeBanned` checks if user permissions (user chapter role) allows for banning specified chapter user.
- Currently `owner` (although such chapter role isn't created) and `organizer` can ban, this is mainly due to `organizer` being seeded, and being relied upon in other places.
- Any comments and nitpicks are appreciated.

### CODE REVIEW

**Comment by gikf** [comment]
I'm having weird issue with making part of test work as intended.
https://github.com/freeCodeCamp/chapter/blob/7f13764f49537592d731486ff7373e6573e73ff7/cypress/integration/dashboard/chapters/users.js#L65
Idea is to find user for test banning, by filtering all members and leaving only those that don't have element with `data-cy=isBanned`. Then pick first from them. That doesn't work however, and once in a while user selected (first `member` on page) for banning will be already banned.

**Comment by ojeytonwilliams** [comment]
@gikf did your last commit fix the test reliability issues you were running into?

**Comment by gikf** [comment]
@ojeytonwilliams yes, although using something else to filter-out users that are not relevant for test.

**Review by ojeytonwilliams — APPROVED** [review]
This looks great @gikf. I'm going to merge this as is and then do a bit of refactoring.  Because we have quite a lot of ids floating around I'd like to use 'named' ids (e.g. `chapterId` not just `id`).  We need that for the authorization logic and I think it'll make some of the logic a bit easier to parse.

**Pull request merged**
