### PR TITLE
Update DOCS

### PR DESCRIPTION
**Pull request by Zeko369**
A lot of changes, pending first check
- [ ] Remove redux
	- [ ] Docs
	- [x] Implementation
- [ ] Move from REST -> GQL
	- [ ] Docs
	- [x] Implementation
- [x] Split app into 2
	- [x] Docs
	- [x] Implementation
- [ ] Change seeding system
	- [ ] Docs
	- [x] Implementation
- [ ] Refactor docker setup
	- [ ] Docs
	- [x] Implementation
- [ ] General docs and README
	- [x] Tech stack in readme
	- [ ] New workflow

### CODE REVIEW

**Comment by tomiiide** [comment]
@Zeko369 Splitting the app into 2, what does that mean?

What are the implications of that for a one-click installation setup for the end users?

**Comment by Zeko369** [comment]
@tomiiide I setup a script to boot up the app in production mode that we'll use to for example on heroku (so only one dyno)

**Comment by allella** [comment]
@Zeko369 I'm still planning to move most of technical details out of the README and into the CONTRIBUTING.md.

The summary of technology in this draft makes sense in the README in this draft.

Is there more you'd like to change on the PR, or shall we merge it in so the README reflects the revised tech stack?

**Comment by allella** [comment]
@Zeko369 someone asked about the role of Jest and it's referenced in #366. Perhaps that's worth inclusion in the docs.

**Comment by vkWeb** [comment]
@Zeko369 I am pushing some docs update here as I just did a fresh installation of chapter (I got Ubuntu). Then once this is merged we can put on remaining docs update in future PRs.

**Comment by vkWeb** [comment]
@Zeko369 I'm merging this we can revisit more docs update later.

**Pull request merged**
