### PR TITLE
fix: lint errors

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

Related to https://github.com/freeCodeCamp/chapter/pull/473.  If this is merged, the CI should pass the lint step.

### CODE REVIEW

**Review by nhcarrigan — APPROVED** [review]
Linting issues appear to be resolved when I test locally.

Note that if we decide to upgrade the linter package to the latest version, we will see some new errors.

**Comment by NorthDecoder** [comment]
To check the commits for this pull request I did:
```bash
git clone https://github.com/ojeytonwilliams/chapter.git
# pulled the branch to be reviewed `fix/lint-errors`
npx recursive-install
npm run lint
docker-compose up
```
The result is:
* no lint errors
* the browser client appears to be running in its existing state
* the browser graphql playground is running in its existing state
🟢

**Comment by ojeytonwilliams** [comment]
> Note that if we decide to upgrade the linter package to the latest version, we will see some new errors.

Yep, there will be, but these all seemed like issues worth fixing.  So, my thinking was that it's worth checking if the upgraded linter catches them and, if not, add the rules back in.

> The result is 🟢 

Nice. Thanks for giving it a round of QA.

**Comment by ojeytonwilliams** [comment]
Thanks for the reviews @nhcarrigan, @NorthDecoder.  I'm going to merge this in so I can keep working on https://github.com/freeCodeCamp/chapter/pull/473

**Pull request merged**
