### PR TITLE
fix(docs): update node version

### LINKED ISSUE #357: Sync package.json and docs
### Describe the bug:

`package.json` has as config:
```json
"engines": {
  "node": "13.x",
  "npm": ">= 6.0.0"
}
```

`README.md` explains: _ Ensure you are installing Node 10 or greater and npm 6 or greater_.

These two are out of sync.

Should `package.json` or `README.md` be updated?

### PR DESCRIPTION
**Pull request by Sushmeet**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

Closes #357

Changes have been made to update the read me with the correct node version.

### CODE REVIEW

**Comment by allella** [comment]
I'm not a node dev, but I recall the [.nvmrc](https://github.com/freeCodeCamp/chapter/blob/master/.nvmrc) was bumped recently to 13.8.0.  Does that make the minimum 13.8.0, or is saying Node 13 sufficient?

**Comment by Sushmeet** [comment]
So the way i  see it is  in  engines  we say the node version should support 13.x.x version. I am not quite sure what that 13.8.0 version is in the  .nvmrc file as the current latest node version  is 13.11.0 here https://nodejs.org/en/ 

So in short the chapters application should be supported on every node version from 13.x.x up until the current 13.11.0 . 

Do you feel my comment conveys that info to the user or wondering If i should be a bit more explicit. Thanks

**Comment by allella** [comment]
@Sonicrida  created the .nvmrc, so perhaps we can get input on this PR?

**Comment by Zeko369** [comment]
@all-contributors please add @Sushmeet for docs

**Pull request merged**
