### PR TITLE
Feature/links as buttons

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

Closes #XXXXX

I was annoyed by the naked links shown in the UI so I went ahead and styled them like buttons. The decision on the variant is yet to be done.
While I was at it, I placed cards within a grid instead of stacking them.

Feedback welcome.

### CODE REVIEW

**Review by vkWeb — CHANGES_REQUESTED** [review]
@Ryuno-Ki 
```
Unhandled Runtime Error
Error: Objects are not valid as a React child (found: Error: Failed to fetch). If you meant to render a collection of children, use an array instead.
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at home/index.tsx:35)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (at home/index.tsx:34)
    in div (at home/index.tsx:31)
    in Home (at _app.tsx:34)
    in div (at PageLayout/index.tsx:11)
    in PageLayout (at _app.tsx:33)
    in ThemeProvider (at _app.tsx:31)
    in ApolloProvider (at _app.tsx:30)
    in MyApp
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
```

**Comment by Ryuno-Ki** [comment]
What command did you run to produce this output?
This way, I can run for myself to produce a clean output.

**Comment by vkWeb** [comment]
@Ryuno-Ki `npm run both`.

**Comment by Ryuno-Ki** [comment]
Okay, investigated the culprit and pushed a fix.
A proper solution should be discussed in #415.

**Review by vkWeb — APPROVED** [review]
All OK design wise. We need to keep upcoming events variant `h3`.

**Comment by Ryuno-Ki** [comment]
> We need to keep upcoming events variant h3.

I didn't change that as far as I can tell.

**Comment by vkWeb** [comment]
```
client/src/modules/home/index.tsx

<Typography variant="h1" component="h1">
  Upcoming Events
</Typography>
```

**Comment by Ryuno-Ki** [comment]
Pushed.

**Comment by vkWeb** [comment]
@Ryuno-Ki We will wait for Tim to review.

**Comment by timmyichen** [comment]
@Ryuno-Ki alright, so I'm getting my local repo set up again - which page(s) are best to see these changes on?

**Comment by Ryuno-Ki** [comment]
I changed these:
- `/`
- `/dashboard/`
- `/dashboard/events/`
- `/dashboard/venues/`

**Comment by timmyichen** [comment]
I only have a few minor comments about the code, but I think the bigger unanswered question is: Do we know what this UI is supposed to look like (cc @QuincyLarson since I'm not sure who's in charge of design)?

Because if not, then I think the best way forward is to leave them as unstyled as possible until we do have designs for them.  With this PR, we're potentially looking at:

1. Having the original, unstyled, links
2. Then having links styled in a way that looks good to user X
3. Then having links styled as is represented in the design, undoing some changes from step 2
(repeat step 2 for whoever else wants to style them)

If at all possible I'd rather just do step 1 and step 3 and avoid adding extra code to the codebase.  If others feel strongly about getting this in I'd happy to do an actual code review.  Alternatively, if you want to pull specific changes out of this PR and into another one (i.e. more detailed error messages), that would unblock #415 without needing the design question answered.

Let me know your thoughts / if this makes sense / etc

**Comment by allella** [comment]
@tomiiide was the most involved with the UI side, most recently on admin interfaces.  @bodo was assisting with some of the UX part of it. https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-August-15,-2020#next-steps

The [Figma prototype](https://github.com/freeCodeCamp/chapter#ui--ux--design-references) would be the closest thing I've seen to design, but I think the concerns have been more around layout and what needs to go on the page at this point.

I believe Quincy's suggestion was to use the Material UI components and not go to any lengths to apply styling for the MVP.

**Comment by Ryuno-Ki** [comment]
I oriented on the Figma prototype. @vkWeb encouraged me to realise some ideas found there.

**Comment by vkWeb** [comment]
@timmyichen Me, @Madalena-15 and several others created the Figma prototype. I think we should keep moving forward with that design. 

Link to prototype: https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=1%3A2&scaling=scale-down

**Comment by Ryuno-Ki** [comment]
Somehow the rebase to fix a merge conflict messed up things. It is broken locally. Don't merge yet. I need more time to investigate what happened.

**Comment by vkWeb** [comment]
@Ryuno-Ki Any updates?

**Comment by Ryuno-Ki** [comment]
Hi @vkWeb.
Sadly no. I'm currently in an … uncertain position at work and would like to focus at this problem before shifting to the issue here.
I'm happy if someone else is picking it up, too.

**Comment by dtwilliams10** [comment]
What's left to be done? I can try to pick it up and get it finished.

**Comment by Ryuno-Ki** [comment]
That would be great, @dtwilliams10,
I _think_ the changes are correct. But I got an error when checking out this branch locally and run it.
Somehow, there are no checks for this PR, so the error would need to be resolved (or otherwise, `master` is broken after merge for everyone).

**Comment by dtwilliams10** [comment]
@Ryuno-Ki Sounds good, I'll pull the branch and see what's what.

**Comment by dtwilliams10** [comment]
Ok, so I checked out the branch and merged in the latest changes from master. The branch seems to be working fine once I corrected the db port to connect to the local db I had running. Is there something in particular I need to be looking for?

**Comment by Ryuno-Ki** [comment]
I guess not. So no changes needed?

@timmyichen's review is still pending, then.

**Comment by dtwilliams10** [comment]
What was needed for this pull request to be merged in? Just waiting on the @timmyichen to finish their review?

**Review by timmyichen — APPROVED** [review]
Code LGTM.  I haven't looked at the figma designs but if they're good then we should be fine to move forward with this.

**Comment by allella** [comment]
Thanks @dtwilliams10 @Ryuno-Ki  and @timmyichen .

This has been merged.  @dtwilliams10 please create a new issue or PR if this needs more work or introduces something unexpected.

**Comment by allella** [comment]
@tomnoland  the errors you reported in the chat are likely related to this PR, which was merged in a few days ago.

> Fyi, the client code currently has some errors in it. To run next build successfully make the following changes:
> Remove extra curly brace EventItem.tsx line 66
> Remove line 50 EventsPage.tsx: className={styles.gridItem}
> Remove line 49 VenuesPage.tsx: className={styles.gridItem}
> ./src/modules/dashboard/Events/components/EventItem.tsx
> ./src/modules/dashboard/Events/pages/EventsPage.tsx
> ./src/modules/dashboard/Venues/pages/VenuesPage.tsx
> After those changes, then execute npm run build and npm run start

Could you see if that's the case and submit a PR with your fixes.

**Pull request merged**
