### PR TITLE
fix: populate rsvp table during init

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

The majority of changes were to the test code, to ensure that a fresh start is tested at least once.  Their organisation is a little messy now, but I'm not sure there's an obviously better approach.

The issue itself was simply that the rsvp table had no entries causing event creation to fail (it tries to connect and fails)

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Sorry for the noise on this PR. I'm at a loss to why it's failing in CI, since it's fine locally.

**Comment by ojeytonwilliams** [comment]
Alright.  The main issue seems to be that two instances of the prisma client are clashing with each other postgres is throwing 

> ERROR:  cached plan must not change result type

quite why, I'm not sure, but once this happens it causes issues with subsequent tests - `seedDb` starts to fail.

**Comment by ojeytonwilliams** [comment]
This *might* just be a problem in testing (since we're not going to be reseting/seeding/syncing the db on the fly in production), but I'm not quite convinced, yet.

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Pull request merged**
