### PR TITLE
chore: replace placeholder in email

### LINKED ISSUE #276: Text for automatic emails notifying participants of subsequent events
Depends on #107

### PR DESCRIPTION
**Pull request by Sboonny**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #276

This isn't tested yet, because I haven't debugged and stuff. I will look if it actually works, then update it later.

I have reached this conclusion while searching for message issue and will come back to this after I am done with message issue

Edit: I have no idea how to tackle the instance domain part 🐰

### CODE REVIEW

**Comment by Sboonny** [comment]
console.log and debugging doesn't work at all, I will try using mailhog to see if this is used, when I look deeper on how this triggered.

**Comment by ojeytonwilliams** [comment]
Hey @Sboonny changes to reminders are pretty low priority right now, since Google Calendar should handle this.  We can revisit this post MVP, but I'm blocking it for now.

**Comment by Sboonny** [comment]
Wanna create discord poll, about deleting the file?

I vote for deleting it, although I am sentimental because it is a challenge that I overcome after a while. it isn't used as you said before so we should delete

**Comment by ojeytonwilliams** [comment]
Delete Reminders.ts? I think it's fine to keep it around.  We do plan to use it after all.

If you're worried that it's a distraction, we can add a big warning at the top of the file to let people know it's not currently used.

**Comment by ojeytonwilliams** [comment]
Closing this as it's tracked in https://github.com/freeCodeCamp/chapter/issues/1771

**Pull request closed without merging**
