### PR TITLE
feat: Updating the Event Card to look more like the mockup.

### PR DESCRIPTION
**Pull request by paizle**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

Updated the look of the Event to match the Figma mockup [here](https://www.figma.com/proto/q7DikyL3N0c4CUWxHNa97i/Chapter-Prototype?node-id=1%3A2&scaling=scale-down).

Added a global Sass stylesheet.

The idea here is that the Event component will have a consistent look when displayed but individual pages may change the display by specifying a parent class or ID on whichever element contains the Event component.

Note that this unfortunately breaks the Next build process in the /client directory. `cd client` `npm run build` because of changes I made to the file in /Chapter/client/src/generated/index.tsx to get some of the data required for the event but I'm not sure how to fix yet. Creating a "Draft pull request" because of this.

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
@paizle this is much closer to the figma mockup and looks a lot better.

I'm not sure about using SASS, though.  I'm not a front-end expert by any means, but we're adding complexity by having both JSS and SASS together.  Do we need to?

> Note that this unfortunately breaks the Next build process in the /client directory.

Yep, there are a few type errors. This should all be a little easier to navigate once the linting, type checking and so on is automated by https://github.com/freeCodeCamp/chapter/pull/473.

**Comment by paizle** [comment]
@ojeytonwilliams I'll look into using the MUI makeStyles for this. I've been trying to find a good reason to use Sass or even CSS styling with MUI but the docs don't really mention the use of external style sheets like these... almost as if it's not really recommended.

I was trying initially to do the Event card styling with MUI Grids but I realized this was not the way to go. Grids are great for laying things out like multiple cards in a list but for fine tuned styling inside each Event card it went better with specific styles and parent/child classes.

I can think of some advantages but if it's too far removed from standard MUI practices then maybe I should try converting the Sass to JSS and see how that goes.

**Comment by ojeytonwilliams** [comment]
> I can think of some advantages but if it's too far removed from standard MUI practices then maybe I should try converting the Sass to JSS and see how that goes.

If you can, I think that would be ideal.  I don't have a strong opinion of SASS vs MUI, it's just that I'd like to keep the number of different technologies down, if possible.

@allella do you know if these are reasonable things to mix? That or know who to ping that might?

**Comment by allella** [comment]
This isn't my stack, so I don't have experience or opinions.  @Ryuno-Ki @vkWeb @tomiiide @katien do any of you have guidance on if we need to steer clear of SASS in Chapter?

**Comment by ojeytonwilliams** [comment]
Hey, I just resolved a few conflicts, so this more up-to-date.  There are a few type issues remaining, but nothing major.

**Comment by vkWeb** [comment]
Hey @allella & @ojeytonwilliams :wave: 

Sorry for replying so late on this, some university related things were going around. 

Regarding Saas, umm, I have no experience with the react ecosystem, so I would say, we should move ahead with what feels best to you and @ojeytonwilliams.

**Comment by paizle** [comment]
I'm biased since I think Sass is great. I think the styles I set up in this case can be converted to JSS but a concern is that this locks these down into the component. In this case I don't think that's necesarily a bad thing since it's a "card" type and the layout isn't too opinionated (it's FLEXible).

I'm still relatively green to Material UI and I don't know much about the interplay with external/global CSS/Sass and if they are meant to work together well. I've been using Sass with Material UI with no problems so far but a global CSS can get out of hand if used not used well.

Ideally, I'd like to try converting this PR to use JSS and see how it goes. Sorry, I have been really busy lately. Once that's done, if I think Chapter can still benefit from using Sass as well, I'll say so.

**Comment by ojeytonwilliams** [comment]
Hey @vkWeb :wave: it's good to hear from you.  I hope uni is treating you well!

> Ideally, I'd like to try converting this PR to use JSS and see how it goes. Sorry, I have been really busy lately. Once that's done, if I think Chapter can still benefit from using Sass as well, I'll say as much.

That sounds perfect.  I'm really not sure what's correct here, it's just that my instincts are towards fewer technologies if possible.  I'm looking forward to seeing what you discover.

**Comment by allella** [comment]
Thanks. Again, not my stack, but the [first blog post that came up exploring the issue](https://drxcheng.medium.com/my-journey-from-css-modules-to-css-in-js-b61ef397e87e) was in favor of JSS + the learning curve.

I'm open to other takes, but here's a summary of the aforementioned opinion piece,

> Material-UI core styling is using JSS. The dependency is built-in so there is no additional bundle size overhead. Furthermore, I have already used some JSS for overriding the MUI theme globally in the code. Although there might be more popular or powerful CSS-in-JS libraries, using JSS here should be the first choice.

and in general using core tech and patterns is typically going to avoid bloat and having to work around edge cases.

**Comment by Zeko369** [comment]
Hi @paizle,
during the last [meeting](https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-April-24,-2021) we decided to use [Chakra-UI](https://chakra-ui.com/docs/getting-started), which is a perfect middle ground (IMO) between writing plain CSS and using a component lib

So you can merge develop branch and refactor your sass into that (You can keep the old MUI stuff, we'll be running dual libs till we move all the MUI stuff over passively)

If you need any help feel free to ping me here or in Rocket Chat or Discord

**Comment by allella** [comment]
@ahmadabdolsaheb we have the [two mockups now listed on the README](https://github.com/freeCodeCamp/chapter/blob/master/README.md#ui--ux--design-references).

I believe this draft PR was made with the Figma mockup, but feel free to use what you can from this if the Figma event card is the direction.

The [mockups from megajon](https://preview.uxpin.com/13c1d07f6dd731123612a8884eb4174459312ac5#/pages/138361235/simulate/sitemap) didn't have a complete event view, but it was more of a list format than a card.

In any case, I wanted to ping you since we have some previous efforts which may or may not be of use.

Also, you might be able to pull in some help from previous contributors like @paizle now that we have more mockups and more interfaces close to being merged in, like #637

**Comment by ojeytonwilliams** [comment]
Hey, this looks to have gone stale.  Please feel free to reopen if you have a chance to work on it!

**Pull request closed without merging**
