### PR TITLE
Add initial SchemaSpy to the gh-pages branch. Remove other docs.

### LINKED ISSUE #54: Schema image / ER Diagram is out of date
Whilst I like the image of the schema, it's not auto-generated on updates to the SQL script so it could be misleading.

The version there is generated by a tool called DataGrip from JetBrains which is [not free](https://www.jetbrains.com/datagrip/buy/#commercial?billing=yearly).

### PR DESCRIPTION
**Pull request by allella**
The other docs will still exist in the main branch of the repo, at least for now. 

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [] My pull request targets the `master` branch of Chapter. This purposely targets the gh-pages branch.

Closes #54 

For now, it's easy enough to generate the schema and push updates to this gh-pages branch.

Eventually, as outlined in #54 we should be able to run a more automated solution to update the schema, like with the SchemaSpy Docker image.

### CODE REVIEW

**Comment by vkWeb** [comment]
@allella I don't know anything about schemaspy :sweat_smile: (and this PR looks quite large) so we'll need to wait till this weekend for my review. Others are welcome to review / merge if required. 

Sorry Jim for the delay!

**Comment by vkWeb** [comment]
@allella Ohh, I just read the comments in that issue. I see now. Running and reviewing in a minute.

**Comment by allella** [comment]
Thanks. This is an auto generated atatic site.  I has just hoping you'd
confirm things look good on the gh-pages targeting.

**Review by vkWeb — APPROVED** [review]
@allella All looks good. :tada: 

I first ran schemaspy on my linux system to see how it renders and then I pulled your PR to see if it matches that. And it's perfect.

:beers: 

chapter database schemaspy render

**Comment by vkWeb** [comment]
Jim, we've successfully deployed at: https://freecodecamp.github.io/chapter/index.html :green_circle:

**Pull request merged**
