### PR TITLE
Testing a fix for a gh-pages branch merge conflict

### PR DESCRIPTION
**Pull request by allella**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [] My pull request targets the `master` branch of Chapter. This purposely targets the _gh-pages_ branch

I'm checking to resolve a merge conflict client/src/modules/dashboard/Events/components/EventItem.tsx when I checked out this branch.

It may have been related to a permissions issue on my end. Or, perhaps it's something we'll have to deal regularly.  Trying to figure it out.

### CODE REVIEW

**Comment by allella** [comment]
@vkWeb I checked out the gh-pages branch again after the merge to see if I could sync up and then branch off the gh-pages.

There was a merge conflict on the client/src/modules/dashboard/Events/components/EventItem.tsx file, which was part of a commit to master between the time I opened the PR and the time you closed it.

This may have been a one-off thing, but I want to run a test and see.

I removed client/src/modules/dashboard/Events/components/EventItem.tsx from the _gh-pages_ branch and created this PR to see what it would look like.  I think it would be fine to merge this into the gh-pages branch.  My main question is if we'll have to regularly do when checkout out gh-pages for updates.

**Comment by allella** [comment]
I suspect gh-pages should operate relatively independent, but when you start switching between master and gh-pages it may cause some new files on master to look like they are deleted.

A workaround may be to not mix development of the two branches in the same local directory.

The merge conflict I'm seeing is

image

**Comment by allella** [comment]
For instance, I'm wondering if having a separate directory for working on the gh-pages, without master being cloned or pulled, would simplify things

```
mkdir chapter-ghpages
git init
git remote add origin https://github.com/allella/chapter.git
git remote add upstream https://github.com/freeCodeCamp/chapter.git
git pull upstream gh-pages
git checkout gh-pages
git branch fix/gh-pages-test
```

and then changes could be made to the local PR branch (ex. fix/gh-pages-test), committed, and pushed to the origin
```
git commit -m 'Did somethings to Github pages'
git push origin fix/gh-pages-test
```

And then do a PR request on Github as normal, targeting the gh-pages branch.

**Comment by allella** [comment]
This may not be necessary, but the merge conflict was unexpected, so I'm trying to figure out if we need to avoid potential merge conflicts since switching a single directory between master and gh-pages may cause some unwanted artifacts from the bulk adds and deletes.

**Comment by vkWeb** [comment]
@allella umm, I get it. Yeah this happens with git pull very often. Git pull stops whenever it looks like something gonna break (a merge conflict).

That's why I always personally use hard reset (like below I've shown) to get in sync with upstream. 
```bash
# Fetch all resources from upstream
$ git fetch upstream

# Sync local master with upstream (optional step when you only want to work on gh-pages stuff)
$ git reset --hard upstream/master

# We are on master right now. Create and switch to a new branch.
$ git checkout -b gh-pages-fix

# Reset the branch with upstream/gh-pages
$ git reset --hard upstream/gh-pages

# Done. Continue doing your work, follow normal PR creation flow like git add, git commit, git push origin gh-pages-fix.
```

Actually, when we do `git pull upstream gh-pages`, git fetches from upstream and merges all those commits to our local gh-pages-fix branch which can raise conflicts scenario.

With git reset --hard, we make our gh-pages-fix branch point to the latest commit where upstream/gh-pages is, then it makes our working directory exactly look like what it was in that latest commit destroying everything else permanently. 

So, using the commands I listed above should solve all our problems.

**Comment by vkWeb** [comment]
And when you want to review PRs, here are the commands I use: https://gist.github.com/vkWeb/dcec82b079f1edc19478ddb58b0ffc5e. 

It is the simplest and the most elegant way to test PRs locally. It's just two git commands.

**Comment by allella** [comment]
Thanks. I'll try the hard-reset. I have an alias that does that on master, but I didn't do it on the gh-pages branch.

If for some reason that still comes up with a conflict, then the steps I posted to create a new directory without the master branch checked out seemed to get around the merge conflicts as well.

**Comment by allella** [comment]
Thanks @vkWeb. I haven't run through it all the way, but your suggestion makes sense and I've incorporated them into [comment on how to run SchemaSpy](https://github.com/freeCodeCamp/chapter/issues/54#issuecomment-799653569).

I think [creating a directory without master and checkout out gh-pages](https://github.com/freeCodeCamp/chapter/pull/455#issuecomment-800348660) would also work, but it's more steps and things to remember.

I'll plan to move the SchemSpy stuff into a more formal doc once it's been validated a couple times.  I'll probably be the one running it manually for now.

**Comment by vkWeb** [comment]
@allella yes that sounds good. If you run into issues then feel free to mention me anytime! :smile:

**Pull request closed without merging**
