### PR TITLE
feat: add Gitpod configuration

### LINKED ISSUE #384: Setup Development Environment with Gitpod, Github Codespaces, or Similar
@QuincyLarson since our dev setup isn't really the easiest, what do you think about trying to enrol this project in the beta and we setup a simple codespaces template so people would be 2 clicks away from contributing compared to a docker, VScode, other stuff steps away

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

This configuration should set up everything needed to run and edit the site in Gitpod.

Closes #384

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
There's an issue, I think because of how prebuilds work, means the graphql server cannot be reached. I'll take a look.

**Comment by allella** [comment]
Nice work. I don't have the experience to review this but I wanted to mention that this closes #384.

**Comment by ojeytonwilliams** [comment]
Thanks, I've updated the OP.  

I'm reasonably happy with how it's working from a Gitpod perspective (everything opens up pretty quickly), but it could definitely use an experienced eye.

**Review by vkWeb — APPROVED** [review]
I tested the environement. To me, it looks amazing. Great work @ojeytonwilliams! :tada:

**Comment by ojeytonwilliams** [comment]
Thanks for the review, @vkWeb, I'm glad you like it!  Are there any other steps I should take?  I'm not sure if there's a Chapter policy for reviews/merging etc.

**Comment by allella** [comment]
@katien would you like to review this PR?  (also, I'm using this as a test to see if you show in the Reviewers after I've mentioned you, or when you reply.  Thanks

**Comment by vkWeb** [comment]
> Thanks for the review, @vkWeb, I'm glad you like it! Are there any other steps I should take? I'm not sure if there's a Chapter policy for reviews/merging etc.

@ojeytonwilliams Yea - it was my pleasure Oliver :) 

I don't think you need to do anything more, a PR with descriptive title / commits and working code is good to go. Umm, there's no concrete policy on PR merging as far as I know. Usually we merge a non-trivial PR after review by Tim (@timmyichen) or Fran (@Zeko369), they are the most comfortable with the codebase. 

I'll merge this one as there's no breaking changes :tada:

**Comment by vkWeb** [comment]
@katien you should still test the enviornment and see if it's working as expected. In case of any bugs please open an issue and we'll discuss a fix. 

Thanks for everything you're doing for Chapter :)

**Comment by allella** [comment]
@ojeytonwilliams I'm not sure what's supposed to be shown, but the Gitpod bot has a broken image link when I created PR #446 for a simple docs update.
https://github.com/freeCodeCamp/chapter/pull/446#issuecomment-792888188

**Pull request merged**
