### PR TITLE
add initial schema ddl + diagram

### PR DESCRIPTION
**Pull request by dmmulroy**
Based on the requirements of the README I threw together an initial postgres schema to get the ball rolling.  Let me know what ya think

### This diagram is outdated, see conversation below or view the changed files
ddl diagram

### CODE REVIEW

**Comment by MirzaChilman** [comment]
I think you are missing a field to track our users attendance rate.

**Comment by dmmulroy** [comment]
> I think you are missing a field to track our users attendance rate.

updated: 

image

**Comment by kaushalgautam** [comment]
@dmmulroy, what did you use to create the schema?

**Comment by QuincyLarson** [comment]
@dmmulroy This is everything I hoped for and more. I'm also going to add this diagram to the Readme to give people a better idea of what we're building.

**Comment by dmmulroy** [comment]
@kaushalgautam [DataGrip](https://www.jetbrains.com/datagrip/)

**Comment by kaushalgautam** [comment]
@dmmulroy thanks mate 👍

**Comment by nik-john** [comment]
@all-contributors please add @dmmulroy  to doc

**Pull request merged**
