### PR TITLE
fix: stop dev login happening automatically

### LINKED ISSUE #1547: Auto log in when navigating to a page using browser urls
While testing https://github.com/freeCodeCamp/chapter/pull/1540/commits/2fc561fae84bc71cea7a26edeb0cfcf39dfe906a, I notice that if you navigate using browser url, instead of action driven navigation (clicking a button), you will be automatically logged in.

I am wondering if this is intended and if it can linger to production? 

To reproduce:

1- open `localhost/3000`
2- log out
3- type in the browser url `localhost/3000/chapters`

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes https://github.com/freeCodeCamp/chapter/issues/1547

### CODE REVIEW

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Comment by ojeytonwilliams** [comment]
Interesting.  Could you check main and see if you see the same bugs?

**Comment by gikf** [comment]
There's nothing stopping from viewing these pages, but none of the actual action (edit, adding new) should work.

**Comment by ojeytonwilliams** [comment]
Ah, got you.  That's tracked in https://github.com/freeCodeCamp/chapter/issues/1534

**Comment by Sboonny** [comment]
Oh, I am sorry for false alarm, I thought because I was navigated to sponsor page, and this test pass `lets an instance owner edit sponsors`, and for some reason I thought it wasn't login 😞, that people can actually edit and create new sponsor.

I should have been more through 🤦👍

**Review by gikf — DISMISSED** [review]
Seems to work and can help with at least one flaky test :ok_man: :+1:

**Comment by gikf** [comment]
Failing tests start working again after changing setup to run `beforeEach` https://github.com/ojeytonwilliams/chapter/blob/59176a2f8e38456525d6382a7c7aa22cc09dbab4/cypress/e2e/dashboard/chapters/chapters-index.cy.ts#L14

**Comment by ojeytonwilliams** [comment]
Thanks @gikf, that fixes it. We *could* use cy.session to preserve the login, but that's still marked as experimental so I'm being cautious.

**Comment by gikf** [comment]
It was surprising that this changed, it's not a big deal now, when that behavior is known.

**Comment by Sboonny** [comment]
@gikf I am happy to revert this back, my worry was it's a bug, and it may damage production while it's close. 

Reading the comment, my worries are unnecessary. 👍

**Comment by ojeytonwilliams** [comment]
@Sboonny there's no need to revert.  The automatic logging in was a bug which was, at best, confusing.

**Pull request merged**
