### PR TITLE
Fix: Remove unused node-typescript to fix node version conflicts

### LINKED ISSUE #165: Question: Is node-typescript necessary?
I was looking through the codebase and trying to run the application locally on my system. I notice that installing packages fail because the Chapter engine is set to node version 10 but one package we are using, `node-typescript` wants node version **0.8.x**. 

https://www.npmjs.com/package/node-typescript

This package seems to be 7 years old and the github repo is no longer available. Is this something that we are using? Can I remove it? I am not familiar with node + typescript but from what I can tell, I don't see it being used anywhere.

### PR DESCRIPTION
**Pull request by Sonicrida**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

Closes #165

As discussed in #165 , the `node-typescript` package wasn't being used and was also causing node version conflicts so I have removed it from the project.

### CODE REVIEW

**Comment by vkWeb** [comment]
@Sonicrida Looks good to me. Thanks for cleaning this up ;)

**Comment by nik-john** [comment]
@all-contributors please add @Sonicrida  for maintenance

**Comment by nik-john** [comment]
@all-contributors please add @Sonicrida for maintenance

**Comment by nik-john** [comment]
@all-contributors please add @Sonicrida for maintenance

**Pull request merged**
