### PR TITLE
Replaced Material UI references with ChakraUI in All Pages/Components

### PR DESCRIPTION
**Pull request by Ravichandra-C**
1. Imported the Chakra component
2. Removed the Material Ui component
3. Used the chakra component .
4. Removed the Material UI references from Chapter Page
5. Removed Material UI references from Venue Page

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Partial fix for issue #608

Please let me know if the changes are good, I'll make changes for other components as well.

Screenshots of old page vs new Page

Old Page :

image

New Page : 

image

### CODE REVIEW

**Comment by allella** [comment]
I'm not familiar with Material UI or Chakra, so I'll defer to @Zeko369 or @ojeytonwilliams .

As far as the button, I notice this button is the full width of the form.  I don't think it's critical, but I'd be open to changing the label of the button.  Either all-caps or capitalizing the "C" in Chapter.  Or, even renaming it so something like "Save Chapter Changes", but it's probably fine to keep it simple as just "Update Chapter".

I did notice the button on the _Event_ edit form doesn't match, so perhaps we can make these form buttons match as part of the transition to Chakra.
image

**Comment by allella** [comment]
I should mention, that I think the full-width button looks and operates better than the small button. Though, I'm also not a UI expert.

**Comment by Ravichandra-C** [comment]
> perhaps we can make these form buttons match as part of the transition to Chakra.

Sure @allella , I'll Update the button on the Edit Events Page to match the Edit Chapters Page.

**Comment by Ravichandra-C** [comment]
> As far as the button, I notice this button is the full width of the form. I don't think it's critical, but I'd be open to changing the label of the button. Either all-caps or capitalizing the "C" in Chapter. Or, even renaming it so something like "Save Chapter Changes", but it's probably fine to keep it simple as just "Update Chapter".

I'll update the label to "Save Chapter Changes" on the UI

**Comment by allella** [comment]
@Ravichandra-C I'd suggest we update the buttons on the Event and Venue forms to also match the pattern of the Chapter button.

So, "Save Event Changes" and "Save Venue Changes"

**Comment by Ravichandra-C** [comment]
@allella I've made the requested changes to Update Event and Update Venue Buttons

image

image

**Comment by allella** [comment]
@Ravichandra-C I loaded this branch and the only question I have is if the browser console error below is something we can fix in this PR, or if it's a broader issue that will be fixed when MUI is replaced.

image

**Comment by Ravichandra-C** [comment]
@allella Its because of the function name change in the MUI theme, Once we replace the MUI completely we will no longer have that error message.

**Comment by allella** [comment]
@Ravichandra-C are you planning more commits on this PR, or is it ready to merge?

**Comment by Ravichandra-C** [comment]
@allella This PR is ready to merge, but that issue #608 is not completely fixed . Could you please merge these changes?
There are 4 more pages/components that needs to be  modified.
Here is the list of Pages that still needs to be updated.
1. client/src/pages/_app.tsx
2. client/src/pages/_document.tsx
3. client/src/modules/dashboard/Events/components/EventItem.tsx
4. client/src/modules/dashboard/Venues/components/VenueItem.tsx

I'll be making a separate PR for the above pages.

**Pull request merged**
