### PR TITLE
Put schema diagram in a dropdown

### PR DESCRIPTION
**Pull request by ScottBrenner**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

The schema diagram is huge! Proposing moving into a dropdown like this to save space.

_courtesy https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61_

### CODE REVIEW

**Comment by allella** [comment]
Is it easy to make that "Click here" look like an anchor/link and then remove the words "Click here"?

**Comment by ScottBrenner** [comment]
I don't quite follow, can you expand? (get it? haha .. )

This dropdown thing uses native HTML tags, so if it's doable with HTML it's doable here!

**Comment by allella** [comment]
If that's the case then perhaps try turning the "View a diagram illustrating the proposed schema for Chapter" into a link with just a path/href="#". That should make it look like a link and then we don't need to use the dreaded "Click here"

**Comment by ScottBrenner** [comment]
Ah that makes sense - looks like it works here in GitHub comments

<details>
<summary>
  <a href="#">
    View a diagram illustrating the proposed schema for Chapter.
  </a>  
</summary>
<br>

a diagram illustrating the proposed schema for Chapter
</details>

but it doesn't render in the actual document:

image

_code:_
```
<details>
<summary>
  <a href="#">
    View a diagram illustrating the proposed schema for Chapter.
  </a>  
</summary>
<br>

![a diagram illustrating the proposed schema for Chapter](data/schema.png)
</details>
```

**Comment by allella** [comment]
Alright, I guess people might know the arrow is an expand. I think a (+) is another pattern.

Maybe we just say "Expand to view...".

It just pains me to see "Click here". It a 1998 design pattern and cousin to the "Under Construction" .gif

**Comment by ScottBrenner** [comment]
Roger that! https://github.com/freeCodeCamp/chapter/pull/132/commits/132c982f3511f6d837447bbbbe5d2ab2d7994d1d

**Comment by vaibhavsingh97** [comment]
waiting for another approval before merging

**Pull request merged**
