### PR TITLE
feat: send emails to rsvps on event cancel

### PR DESCRIPTION
**Pull request by gikf**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Still required:
- [ ] Email text.
- [x] Tests?
- [ ] Anything else?

Related to #100

---
Draft adding sending emails to rsvps when event is cancelled.
- Email is send to rsvps that are not cancelled. That means those confirmed or in waitlist. Note in generated data there might be generated rsvps with `cancelled: true`, but this doesn't seem to be displayed in the client right now.
- I've initially added permission check, similar to one in other resolver, based on `user.user_event_roles`, but as that's going to be handled by authorization I've removed it.
- Tested on local fork.

### CODE REVIEW

**Review by ojeytonwilliams — COMMENTED** [review]
Don't worry about the text for this PR, placeholders are fine for now.

Tests would be great, though!  

https://github.com/freeCodeCamp/chapter/blob/e0cac15bc75df2a3f1d8b971f4d00065690eaab8/cypress/integration/dashboard/events.js#L37

has some pretty similar logic, so might be worth a look.

One thing I was thinking about was changing RSVPs to be in a single 'state' (Going, OnWaitlist, Cancelled, etc), rather than having multiple boolean states.  Something like this: https://dbdiagram.io/d/61d5605b3205b45b73d7b04a Reason being, the RSVP can only be in a single state at once (you can't be on_waitlist and cancelled, say), so I think a single state should be easier to reason about. Since you've just been looking at rsvps, I wondered if you had any thoughts on this.

Sorry for the slight tangent and thanks for working on this!

**Comment by gikf** [comment]
Thanks for the lead on tests, I'll take a look there.

I saw your issue about RSVPs status #783, I'd agree having status as a single field most likely will simplify some things and help avoid some awkwardness. Like determining if somebody is confirmed/going by checking both on_waitlist and cancelled.

**Comment by ojeytonwilliams** [comment]
No problem, thanks for taking a look.  

> I saw your issue about RSVPs status

Cool, I wasn't sure if you'd have seen that, since there's been a lot of discussion. Anyways, it's not something to worry about here, but I appreciate the feedback.

**Review by ojeytonwilliams — APPROVED** [review]
Nice one, @gikf. This LGTM :+1:

**Pull request merged**
