### PR TITLE
feat: event subscription status

### PR DESCRIPTION
**Pull request by gikf**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

---
- Displays event subscription status and allows changing it on event page.
- That's possible after `EventUser` is created - it depends on Rsvping to the event (actual rsvp status doesn't matter)
- Adds basic test.

### CODE REVIEW

**Comment by gikf** [comment]
To be honest I think I'd like that not only for subscribing to event, but also in other places. Like Rsvping or subscribing to chapter.

**Comment by gikf** [comment]
:+1: I'll try do that today, or tomorrow.

**Comment by ojeytonwilliams** [comment]
Awesome, no rush at all.

**Review by ojeytonwilliams — APPROVED** [review]
Thanks @gikf this looks great :rocket:

**Pull request merged**
