### PR TITLE
test: getId util

### PR DESCRIPTION
**Pull request by gikf**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

---

- Adds tests for `client/src/util/getId.ts`

### CODE REVIEW

**Comment by ojeytonwilliams** [comment]
Thanks for adding the tests.  They made me wonder if we should be returning 1 by default. For one thing it's mostly used like this:

```js
const id = getId(router.query) || -1;
```

 I think it makes more sense to throw an error if there's no id.  At least for now - we can come up some more sensible approaches later.  What do you reckon?

**Comment by gikf** [comment]
Sure, I'll make PR with throwing and update tests once that's in.

**Comment by ojeytonwilliams** [comment]
It is, yeah.  We can always fold these into that PR if it's easier.

No rush, either way.

**Comment by gikf** [comment]
Closing as well, since #1396 removed `getId` util.

**Pull request closed without merging**
