### PR TITLE
feat: create Google meet for new calendar events

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

To keep things simple, this adds meets to all events.  We can improve things by only creating them for online events

### CODE REVIEW

**Comment by gikf** [comment]
Couple more general questions - how does the permissions for accessing the meet later work? Does everybody added to the event in the calendar automatically are allowed to enter that _meet_? What with those not subscribed to event, would they get allowed to enter when having link to the meet, or would it be needed to manually add them permission?

**Comment by ojeytonwilliams** [comment]
> Does everybody added to the event in the calendar automatically are allowed to enter that meet?

Yes, exactly that.  If you're on the Calendar Event's attendee list, you can go into the meet without the meet creator needing to let you in.  That includes if you've cancelled your attendance, but not if you've been removed from the Event.

> What with those not subscribed to event, would they get allowed to enter when having link to the meet, or would it be needed to manually add them permission?

If you don't RSVP the only way in is if you're manually allowed in.  My understanding is that the creator or anyone in that creator's workspace can do that, but if they're not in the call there's nothing to be done. I'll test this properly once it's live.

**Comment by gikf** [comment]
> Yes, exactly that. If you're on the Calendar Event's attendee list, you can go into the meet without the meet creator needing to let you in. That includes if you've cancelled your attendance, but not if you've been removed from the Event.

That's very nice.


> If you don't RSVP the only way in is if you're manually allowed in.

I mean RSVPed, but not subscribed to event. Or am I confused and subscription status doesn't affect being added to attendees in calendar event :thinking:

**Comment by ojeytonwilliams** [comment]
> subscription status doesn't affect being added to attendees in calendar event

The fact that even you aren't sure about this means it's way too confusing! I'll see what I can do to clarify on the UI, at least.

So, subscription only affects email notifications _from Chapter_:

- If I unsubscribe from a chapter then I won't get notified about new events in that chapter.
- If I unsubscribe from an event then I won't get notified by Chapter about changes to that event 

Google operates separately. So, imagine you've RSVPed then unsubscribed from a Chapter event, but you've also accepted the invitation that Google sends. Then you'll be notified about changes to the Google Calendar Event itself, depending on how you've configured your notifications for that Google account.

There's a bit more context here: https://github.com/freeCodeCamp/chapter/issues/1670

**Comment by gikf** [comment]
That what I found when looking at code. I could swear calendar event attendees list was changed when user subscribes/unsubscribes. I even made issue related to it! #1937

**Comment by ojeytonwilliams** [comment]
>  I could swear calendar event attendees list was changed when user subscribes/unsubscribes

It probably did at one point! Right now it just adds them to the Calendar event if it exists.

**Review by gikf — APPROVED** [review]
LGTM :+1: 

I was wondering if api won't complain about always using the same `requestId` (`MEET_ID`), for multiple calendar events, but no troubles when testing it.

**Comment by ojeytonwilliams** [comment]
> I was wondering if api won't complain about always using the same requestId (MEET_ID), for multiple calendar events, but no troubles when testing it.

Yeah, it's a bit odd, but I think it just needs to be unique for that event.  So, if you want to create multiple 'conferences' you need multiple ids, but otherwise it doesn't seem to matter.

**Pull request merged**
