### PR TITLE
feat: switch from sendgrid to ses

### PR DESCRIPTION
**Pull request by naomi-lgbt**
- [X] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [X] My pull request targets the `main` branch of Chapter.

Closes #XXXXX

This moves us over to SES for our production demo.

Some things for @ojeytonwilliams:

- [ ] What address do we want to send emails from?
- [ ] Do we want any kind of try/catch error handling on the send call?

### CODE REVIEW

**Comment by allella** [comment]
I know fCC is going to use the mail service that makes the most sense and whatever is easiest makes sense for the dogfooding-phase. The Sendgrid-specific package was included for staging and now an AWS specific package for production.

Though, we did decide to use SMTP as the default since the protocol is likely to be supported by the vast majority of relay servers and wouldn't require including other packages unless someone adds more packages to their instance.

I suspect this doesn't prevent other future instance owners from using SMTP, but I'm more generally curious if it will be reasonably easy to allow other instances to exclude and include packages to fit their needs without bloating the package.json.

Linking this to #1269  and https://github.com/freeCodeCamp/chapter/issues/283 for future reference.

**Comment by ojeytonwilliams** [comment]
>  I'm more generally curious if it will be reasonably easy to allow other instances to exclude and include packages to fit their needs without bloating the package.json.

Not easily, to be honest.  npm doesn't, to my knowledge, allow for conditional installation. That said, for now I don't think we need to worry too much about the size of the images.  They're not big enough to be causing problems.

I chatted with Naomi a little and we should be fine to keep all three providers available.  There's not a huge amount of extra code to maintain, so I think it's worth it to keep the flexibility.

Which is to say, SMTP support isn't going anywhere.

**Comment by ojeytonwilliams** [comment]
> What address do we want to send emails from?

Can we use `CHAPTER_EMAIL` for all the providers?  If they can cope with "Name <email@add.ress>" that would be perfect.  

> Do we want any kind of try/catch error handling on the send call?
 
Yeah, please. If you could use https://github.com/freeCodeCamp/chapter/blob/main/server/src/util/redact-secrets.ts and log the errors, that's perfect.

```
console.error(inspect(redactSecrets(e), { depth: null }));
```

is how we've been doing it.

**Comment by naomi-lgbt** [comment]
> Can we use `CHAPTER_EMAIL` for all the providers? If they can cope with `"Name [email@add.ress](mailto:email@add.ress)"` that would be perfect.

I'm not sure about the mailto formatting - I know that both Sendgrid and SES accept `Naomi <naomi@freecodecamp.org>`, though.

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1: 

Thanks, @naomi-lgbt!

**Pull request merged**
