### PR TITLE
Improve Docker Mode, Manual Mode, Node Version, Database, Postegres Sections of CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by allella**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

This addresses most of the issues outlined in #447.

The main changes are:
* splitting the "Contributing Code" steps from the "Running the Application" steps
* clearly defining "Docker Mode" versus "Manual Mode" steps
* improving the Database docs
* making it more clear how to view the website and API docs once the app is running

I'm sure there are some typos remaining, but I wanted to get this in front of others for review to make sure the overall direction is agreeable.

### CODE REVIEW

**Comment by allella** [comment]
@paizle @dtwilliams10 I could use fresh eyes on this if you have time to review it.

Github won't let me tag reviewers until they are involved in the conversation.

**Comment by allella** [comment]
I am curious if "Step 1 - Install Node and Run npx" of the **Running the Application** section is specific to the **Manual Mode** or if **Docker Mode** also needs Node installed locally.  I'd assume the Docker container would install node, but I don't know Docker or Node and haven't tested **Manual Mode**.

**Comment by paizle** [comment]
@allella I might be in the same boat as you with regards to Docker and node. Right now I haven't gotten the Docker setup working so I'm using the manual setup. I was working a bit with Tom Noland (hope I'm spelling that right) on the Docker setup and got a bit further with his help but I think it was still a work in progress and wasn't fully working. I'm not sure if the problems might be with my git bash on windows platform or not.

**Comment by paizle** [comment]
> 
> 
> I am curious if "Step 1 - Install Node and Run npx" of the [**Running the Application**](https://github.com/allella/chapter/blob/docs/contributing-md-docs-tweaks/CONTRIBUTING.md#running-the-application) section is specific to the **Manual Mode** or if **Docker Mode** also needs Node installed locally. I'd assume the Docker container would install node, but I don't know Docker or Node and haven't tested **Manual Mode**.

I'm just testing that now with a fresh install. I think if you are using docker then you might only need to cd into the client directory and `npm install` there. I tried `docker-compose up` in the root without using `npx recursive-install` first and got an error here relating to next not being installed:
client_1  | $ next
client_1  | /bin/sh: next: not found
client_1  | error Command failed with exit code 127.

**Comment by allella** [comment]
I just ran a test on a fresh install and `npx recursive-install` a necessary prerequisite for **Docker Mode**.

It's not a big deal, I just figured everything would run inside Docker and it may only be needed for **Manual Mode**. I suspect there's a way to move that npx / next stuff into the Docker Compose or Dockerfile, but that's beyond me at this point and it's a trivia step to run, so not going to worry about it.

```
client_1  | $ next
client_1  | /bin/sh: next: not found
client_1  | error Command failed with exit code 127.
client_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
chapter-npx-test_client_1 exited with code 127

```

**Comment by paizle** [comment]
It could be noted in the docs that using the local db step requires `yarn db:reset` as well.

**Pull request merged**
