### PR TITLE
Add .nvmrc file for easier local development

### PR DESCRIPTION
**Pull request by Sonicrida**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

Just a quick addition so that developers can more easily change their current node version to match the project configuration.

### CODE REVIEW

**Comment by allella** [comment]
@all-contributors please add @Sonicrida for code.
@all-contributors please add @vaibhavsingh97 for code.

**Comment by allella** [comment]
@all-contributors please add @Sonicrida for code.

**Comment by allella** [comment]
@all-contributors please add @vaibhavsingh97 for code.

**Comment by Shub1427** [comment]
I know I am a bit late to put my thoughts here, but still, If we are starting afresh, shouldn't we be using latest LTS version for NodeJS (v12.13+)? Just a thought

**Pull request merged**
