### PR TITLE
Add seeds

### PR DESCRIPTION
**Pull request by Zeko369**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

Closes #XXXXX

### CODE REVIEW

**Comment by vkWeb** [comment]
@Zeko369 CI is failing. Any updates on this?

**Comment by Zeko369** [comment]
I'm trying to get babel to use a custom config to transpile ES6+ to ES5 so we can use `sequelize-cli`, but kind off hit a wall. I'll push what I have and maybe someone can help

**Comment by allella** [comment]
@Zeko369 is the roadblock on #120 and this issue that sequelize-cli-typescript doesn't work with the stack and so you're punting back to sequelize-cli.  I can try to dig up some new volunteers from #11 if you think this is an issue TS devs or Sequelize devs can get around.

**Comment by QuincyLarson** [comment]
We seem to be blocked by an issue with Babel itself. There are possible workarounds.

**Comment by Zeko369** [comment]
```
require('babel-register')({
  presets: 'es2015',
  plugins: ['add-module-exports'],
});
```

**Comment by Zeko369** [comment]
Killing this PR, I'll do this in a new TypeORM pr

**Pull request closed without merging**
