### PR TITLE
feat: email all interested users on event creation

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
The UI is a bit horrible, but this PR adds another button to /dashboard/events/[id] which sends emails to everyone in that chapter.

### CODE REVIEW

**Comment by allella** [comment]
@ojeytonwilliams I suppose it depends on if this PR is targeting #107  or #99 

#107 seems like it would automatically have the system send emails to _members_ who have previously attended an _event_.

#99 would allow the _organizer_ to email _members_ of a _chapter_ manually and for any reason.

**Comment by ojeytonwilliams** [comment]
True.  I think what I'll do is target #107, since this only allows you to email a canned message.  I'll need to change a few things, but it's not tricky.

It shouldn't take much effort (on the server side, at least) to handle #99, but the UI would definitely take some work.  That would make sense as a separate PR.

**Comment by allella** [comment]
@ojeytonwilliams we have a couple open MVP issues for the text of emails.

#276 is for reminders to go out [2 days prior to the event](https://github.com/freeCodeCamp/chapter/issues/276). 

We have [sample text _event_](https://github.com/freeCodeCamp/chapter/issues/276#issuecomment-596913322) for that use case that can likely be used and tweaked for the initial RSVP and possibly for other messages

**Comment by allella** [comment]
@ojeytonwilliams if /as you, or others are working on the email, then the previous conversations about following / unfollowing a Chapter and unsubscribing from emails should provide good context on the type of links and privacy settings we imagined to make for easy opt-in and opt-out.

That conversation also goes into interfaces on the website and name of buttons, type of buttons and such.

For the emails, we also touched slightly on the security aspects of allowing _members_ to unsubscribe or opt-out without needing to login. For that, something like a secure / unique hash was discussed. Whether that anonymous / hash ideas is the correct approach, or easy to do is up for debate, but I thought to mention it.

The core of those email and UI opt-in / out conversations were on #107 and I tried to summarize the conversation at a few points, like:

https://github.com/freeCodeCamp/chapter/issues/107#issuecomment-596905797
https://github.com/freeCodeCamp/chapter/issues/107#issuecomment-562374895
https://github.com/freeCodeCamp/chapter/issues/107#issuecomment-562432174

**Comment by ojeytonwilliams** [comment]
Thanks for the context, Jim, that's really helpful.  For this PR, I'll keep the scope very limited.  It's just going to send emails to users whenever an event is created if they have `user_chapter_roles.interested` set to TRUE for that chapter.

Does that sound reasonable?  As far as I could see, the discussion was around scheduled notifications, but I think that someone who has set "Unfollow {chapters.name} Notifications" to FALSE would assume that that chapter would stop notifying them entirely.

**Comment by allella** [comment]
@ojeytonwilliams yes, we wanted to account for privacy on emails for an _rsvp_ separately from general updates for the _chapter_ itself, like a new _event_ or even a notice from the _organizer_. 

user_chapter_role.interested and rsvp.interested were added in #374.

[user_chapters was the original table for the _chapter_ level setting, but Timmy Chen removed user_chapters](https://github.com/freeCodeCamp/chapter/pull/335) since [user_chapter_roles](https://github.com/freeCodeCamp/chapter/pull/361) gave us more flexibility on permissions w

I still see [_user_chapters_ in the schema](https://freecodecamp.github.io/chapter/index.html), so I'll have to see if that goes away the next time it's run. I'm wondering if the migrations never deleted _user_chapters_.

**Comment by ojeytonwilliams** [comment]
Okay, cool. I think this is behaving how we want, then.

Regarding *user_chapters*, yes, there's still a migration to create it.  One thing I was considering was that, since we're still in development, it might be worth periodically clearing out the migrations once we're happy that `db:sync` is working.  We've already accrued a fair chunk of migrations and at least one of them (db/migrations/1575817782077-UserChapter.ts) shouldn't exist.

**Comment by allella** [comment]
Sounds good on consolidating the dev migrations. I don't know the best practices on that so I'll defer to others on if / when is a good time to consolidate or clean the migrations.

I believe it's safe to remove _db/migrations/1575817782077-UserChapter.ts_ since there are no models and per #335.  Do you want to do that as part of this PR, or in a new one?

**Comment by ojeytonwilliams** [comment]
> I don't know the best practices on that so I'll defer to others on if / when is a good time to consolidate or clean the migrations.

Neither do I, to be honest.  @Zeko369 do you know what's a reasonable practice here?  I know you pointed out that creating migrations so that we can validate them is a good idea.  As I think about this, I suspect that periodically running `db:drop` and `db:sync` and comparing that with the result of `db:drop` and `db:migrate` could be helpful. That should help us make sure that the migrations are all doing what we want.

Just for the sake of keeping this in scope, I'll create another PR to remove that migration.

**Comment by ojeytonwilliams** [comment]
@allella to keep the number of PRs manageable, I'm going to merge this.  While it doesn't satisfy the user story, I think it's a step in the right direction.

**Pull request merged**
