### PR TITLE
chore: remove firefox downgrading

### PR DESCRIPTION
**Pull request by gikf**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

---

- Removes firefox downgrade in cypress workflow. Cause for adding it is was supposed to be fixed in version `106`, current `108` doesn't have issue either.

### CODE REVIEW

**Comment by Sboonny** [comment]
To save time, I don't think the issue of the failing test is from this PR, but in the main repo. 🤔

**Comment by Sboonny** [comment]
wait does it fails, because there is no past date 🤣 ?

**Review by Sboonny — APPROVED** [review]

**Comment by Sboonny** [comment]
LGTM, Thank you.

**Comment by gikf** [comment]
> Wait, does it fail because there is no past date rofl, in cypress yet?
> 
> image

It's definitely not related with this PR (I hoped at some point, that maybe old firefox version was causing issue, but nah). I cannot reproduce that fail locally. I'm testing couple ideas for selecting date in another way, to see if that fixes issue.

**Pull request merged**
