### PR TITLE
fix: improve developer experience

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- fix: keep logs when watching ts
- fix: make server wait for db to accept connections

The server waiting matters for new users, since the postgres container has a one-time initialisation step which can mean that the app tries to connect before the 5432 port is open.

### CODE REVIEW

**Comment by allella** [comment]
Is this related to the error below on first run?

```
db_1       | 2021-09-14 14:50:01.137 UTC [31] FATAL:  password authentication failed for user "postgres"
db_1       | 2021-09-14 14:50:01.137 UTC [31] DETAIL:  Role "postgres" does not exist.
db_1       | 	Connection matched pg_hba.conf line 99: "host all all all md5"
```

**Comment by ojeytonwilliams** [comment]
I'm not seeing that, no.  

One of the 'fun' things about Docker is that old images and containers stick around and get in the way.  If you don't mind waiting a few minutes while it downloads images again it could be worth trying `docker container rm chapter_app_1 chapter_client_1 chapter_db_1` and `docker image prune -a`.  That'll mean that the next time you `docker-compose up` it will build everything from scratch and (hopefully) deal with that.

**Comment by allella** [comment]
Alright, moving to npm 7 fixed the fsevents issue.

Purging the images corrected that database password issue.

I've confirmed that the _db:reset_ and other scripts are working and connecting to Docker by using  `psql -h localhost -p 54320 -U postgres.` to visualize the changes. It appeared it wasn't working, but probably because a JsonWebTokenError below that appears related to sessions.

If I open the app in an incognito window it resolves. If I don't I get the following errors.  Is this another thing we need to document about clearing cookies / sessions?

`<pre>JsonWebTokenError: invalid signature<br>          at /usr/chapter/server/node_modules/jsonwebtoken/verify.js:133:19<br>          at getSecret (/usr/chapter/server/node_modules/jsonwebtoken/verify.js:90:14)<br>          at Object.module.exports [as verify] (/usr/chapter/server/node_modules/jsonwebtoken/verify.js:94:10)<br>          at userMiddleware (/usr/chapter/server/src/controllers/Auth/middleware.js:17:34)<br>          at Layer.handle [as handle_request] (/usr/chapter/server/node_modules/express/lib/router/layer.js:95:5)<br>          at trim_prefix (/usr/chapter/server/node_modules/express/lib/router/index.js:317:13)<br>          at /usr/chapter/server/node_modules/express/lib/router/index.js:284:7<br>          at Function.process_params (/usr/chapter/server/node_modules/express/lib/router/index.js:335:12)<br>          at next (/usr/chapter/server/node_modules/express/lib/router/index.js:275:10)<br>          at cors (/usr/chapter/server/node_modules/cors/lib/index.js:188:7)</pre>
`

image

image

**Comment by allella** [comment]
Also, clearing my _localhost_ cookies in the browser also fixed the JsonWebTokenError: invalid signature.

**Comment by ojeytonwilliams** [comment]
Sure, that's a common enough issue that, we could add a note to the troubleshooting section.

**Comment by ojeytonwilliams** [comment]
Docker is a bit of a pain.  I'm not 100% convinced it's worth the time we're investing in it at the moment, but it does make it a bit easier for new contributors to get up and running.  Also, we will almost certainly be wanting to use it in production, so it's *probably* worth the hassle.

**Comment by ojeytonwilliams** [comment]
Anyways, I'm happy with the PR as is.  If you're looking to make a start on TROUBLESHOOTING.md, I'll delete the docs commit.  Otherwise I think it's fine for now.

**Comment by allella** [comment]
I think the Prerequisites for npm 7 change is fine.

Nobody had a strong opinion on where to put the troubleshooting, [so I suggested a TROUBLESHOOTING.md or the Wiki](https://github.com/freeCodeCamp/chapter/issues/471#issuecomment-812094442). Though, we can add to the bottom if we don't feel it's going to clutter things.

A link shared in that conversation focused on keeping the How-To documentation to the point. So, if we add Troubleshooting to the CONTRIBUTING.md, then I don't think we'd want to inject it into the How-To for fear of bloating the already numerous steps with more rare conditions.

**Comment by allella** [comment]
Yeah, I'm only messing with Docker because so many people who are new to the project seem to use Windows + Docker or Windows + Git Bash.

I run Ubuntu, so it's more of trying to document their troubles and learn more about Docker's advantage and short-comings in the process.

**Comment by ojeytonwilliams** [comment]
> Yeah, I'm only messing with Docker because so many people who are new to the project seem to use Windows + Docker or Windows + Git Bash.

Yep, it's nice to have a relatively painless setup that doesn't require messing around with postgres.

> I don't think we'd want to inject it into the How-To steps and sections for fear of bloating the already numerous steps with more rare conditions.

I entirely agree.  A few comments at the end of the contributing docs should suffice for now, though, and we can split them off if we find it's getting bloated.

**Pull request merged**
