### PR TITLE
feat: fixed Individual chapter dashboards link to the dashboards for their events

### LINKED ISSUE #2297: Individual chapter dashboards should link to the dashboards for their events
If I `npm run change-user:owner`, login and go to http://localhost:3000/dashboard/chapters/1 I see links to event pages rather than dashboards. For example, if event 1 is in chapter 1, I will see a link to 

http://localhost:3000/events/1
but I should see
http://localhost:3000/dashboard/events/1

### PR DESCRIPTION
**Pull request by dineshigdd**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #2297

1. In `EventList.tsx`, the `Link` component's (for events ) `href` was set to `href={`events/${id}`}`
2. I changed it to `href={`/dashboard/events/${id}`}`

### CODE REVIEW

**Comment by gikf** [comment]
Hey @dineshigdd,

change needs to be made to the events list displayed in the chapter dashboard - `/dashboard/chapters/{id}`. That's `EventList` component - https://github.com/freeCodeCamp/chapter/blob/main/client/src/modules/dashboard/shared/components/EventList.tsx

**Comment by dineshigdd** [comment]
A similar situation exists when you go through the following events
1.) user logged in
2.) select Chapters from the drop-down menu
3.) select an event already added to the chapter

URL that appears right now is http://localhost:3000/events/1.
But, it should be http://localhost:3000/dashboard/events/1

Am I correct? 
This is why I changed 'chapterCard.tsx' initially

**Comment by gikf** [comment]
`ChapterCard` is used on pages available to not logged users and users not being administrators, they'd see errors when trying to follow link to the event dashboard.

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍.

**Pull request merged**
