### PR TITLE
feat: add chapter link to dashboard pages

### LINKED ISSUE #2209: Add mention of chapter to dashboard pages
Chapter is not present on the individual dashboard pages of event and venue in any way (name, link, etc). This makes navigating to chapter inconvenient, as the appropriate chapter needs to be found in a more manual manner.

- [ ] `/events/{id}` https://github.com/freeCodeCamp/chapter/blob/main/client/src/modules/dashboard/Events/pages/EventPage.tsx
- [ ] `/venues/{id]` https://github.com/freeCodeCamp/chapter/blob/main/client/src/modules/dashboard/Venues/pages/VenuePage.tsx

### PR DESCRIPTION
**Pull request by atosh502**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

<table>
	<thead>
		<tr>
			<th>chapter at venue</th>
			<th>chapter at event</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>chapter-at-venue</td>
			<td>chapter-at-event</td>
		</tr>
	</tbody>
</table>

Closes #2209

### CODE REVIEW

**Review by Sboonny — COMMENTED** [review]
You can delete the `Text` elements wrapping the `Link`, because they have no use anymore.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Comment by Sboonny** [comment]
#### :sparkles: :tada: **AWESOME!** :tada: :sparkles:

 Hi @atosh502, thanks for this pull request and for contributing to the code-base for the first time. We are looking forward to more contributions from you in the future.

 Cheers & happy contributing!

**Comment by gikf** [comment]
@all-contributors would you be so nice and add @atosh502 for code?

**Pull request merged**
