### PR TITLE
Chore(markdown): add troubleshooting to contributing.md

### LINKED ISSUE #471: Docs: Add Troubleshooting for CONTRIBUTING.md Steps
## Application Errors
- [ ] Problem: JsonWebTokenError: invalid signature -- Solution: Clear the browser cookies for the _localhost_ domain, or use an incognito browser window to open the site.
- [ ] Problem: Where do application registration and other emails go? -- Solution: All email are captured and saved by Mailhog. Simply open http://localhost:8025/ to see captured emails. For account registration, the email validation link can be opened in the browser to complete the registration process.
- [ ]  The application shows _"Something went wrong relation "chapters" does not exist"_ - Solution:  The [database needs to be initialized](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md#initializing-the-database).
- [ ] The applications shows "_The table `public.chapters` does not exist in the current database."_ or _"Invalid 'prisma_1.prisma.chapters.findMany()"_ -- Solution: The database hasn't been created. Run `npm run db:reset` to clear and re-create the database tables.
 
## Linux Docker Troubleshooting
- [ ] `docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))`
- [ ] Run `sudo docker-compose up` or add non-privileged user to the docker group as described in https://docs.docker.com/engine/install/linux-postinstall/ If Docker was run as sudo before adding your user to the docker group
- [ ] "WARNING: Error loading config file: /home/user/.docker/config.json " see https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

## Node / NPM
- [ ] **Problem:** notsup Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}) - **Solution:** Upgrade to npm version 7 or 8, like `npm install -g npm@latest` or by getting the latest version of NodeJS from your Linux package manager. Or, install [nvm](https://github.com/nvm-sh/nvm).
- [ ] **Problem:** Running _npm i_ gives the error "Module not found: Can't resolve 'framer-motion'" - **Solution:** Upgrade to npm version 7 or 8, like `npm install -g npm@latest` or by getting the latest version of NodeJS from your Linux package manager. Or, install [nvm](https://github.com/nvm-sh/nvm).
- [ ] **Problem:**
```npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename '/usr/lib/node_modules/npm'
 or 
Error: EACCES: permission denied, rename '/usr/bin/npm'
```
**Solution:** https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally or else https://stackoverflow.com/a/51024493
- [ ] If using Windows / WSL + Ubuntu Terminal, "npx /bin/sh^M bad interpreter: No such file or directory" likely happens when Node.js is already installed on Windows, but it also needs to be [installed within the Linux subsystem / terminal](https://nodejs.org/en/download/package-manager/), such as [installing it with _apt_ on in Ubuntu](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions).

## ElephantSQL
- _Error during schema drop: QueryFailedError: must be owner of view pg_stat_statements_ while running _npm run db:reset_ - Solution: the free tier of ElephantSQL doesn't allow concurrent connections, so it's necessary to run database commands one-at-a-time, like _npm run db:drop_ then _npm run db:sync_ and then _npm run db:seed_. Alternatively, a paid plan on ElephantSQL would avoid this issue. - via https://github.com/freeCodeCamp/chapter/issues/762

## General Docker Troubleshooting
- [Linux](https://docs.docker.com/engine/install/linux-postinstall/)
- [Windows](https://docs.docker.com/docker-for-windows/troubleshoot/)
- [Mac](https://docs.docker.com/docker-for-mac/troubleshoot/)
- [ ] Make sure Docker isn't already running and bound to port 54320 - ERROR: for chapter-npx-test_db_1  Cannot start service db: driver failed programming external connectivity on endpoint chapter-npx-test_db_1 (....): Bind for 0.0.0.0:54320 failed: port is already allocated. ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint chapter-npx-test_db_1
- [ ] To shut down Docker on Linux, press Ctrl + C in the terminal where it was started.
- [ ] To purge old images, which can sometimes be the source of errors, run `docker-compose rm && docker image prune -a`

### WSL
- [ ] [General WSL troubleshooting](https://docs.microsoft.com/en-us/windows/wsl/install-win10#troubleshooting-installation)
- [ ] "WSL2 Installation is Incomplete" - Follow the steps to install the missing component
- [ ] WslRegisterDistribution failed with error: 0x80070057 - this is common on older CPUs which does not support Virtulization, HyperV or SLAT - Solution: Open Powershell and change back to WSL 1 using ``wsl --set-default-version 1``

### Windows Docker Troubleshooting
- [ ] "Docker Desktop requires Windows 10 Pro/Enterprise (######+) or Windows 10 Home (#####.####+)" - Windows 10 is running an old / unsupported version and needs to be updated before Docker will install.
- [ ] "Failed to execute script docker-composer"  - Solution: Start Docker Desktop via the Windows Start Menu and restart Git Bash
- [ ] Docker / WSL2 consumes all your system's RAM and is very slow - [Limit resources](https://medium.com/@lewwybogus/how-to-stop-wsl2-from-hogging-all-your-ram-with-docker-d7846b9c5b37)
- [ ] "Windows Defender Firewall has blocked some features of this app"  - Allow Access

### PR DESCRIPTION
**Pull request by Sboonny**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Closes #471

---

OverAll view: https://github.com/Sboonny/chapter/blob/choreadd-troubleshooting-to-CONTRIBUTING/CONTRIBUTING.md#troubleshooting

<details>
 <summary>Images preview</summary>

image

---

Application errors

image

---

Linux Docker Troubleshooting

image

---

Node / NPM Troubleshooting

image

---

ElephantSQL Troubleshooting
 
image

---

General Docker Troubleshooting

image

---

WSL TroubleShooting

image

---

Windows Docker TroubleShooting

image

</details>

### CODE REVIEW

**Comment by allella** [comment]
@Sboonny this looks like a great start. It's been on my to-do list for awhile and I think the idea of trying to do a complete job of it from the start has kept from getting over the hump.  The momentum of this PR is very helpful.

It may be the case that

> Something went wrong relation "chapters" does not exist.

and

> The table public.chapters does not exist in the current database or Invalid'prisma_1.prisma.chapters.findMany()

have the same solution, so perhaps we can combine those two messages under the same solution.

**Review by allella — APPROVED** [review]

**Comment by Sboonny** [comment]
If you want me to help with something, feel free mention it. Instead of opening another pr

**Comment by allella** [comment]
@Sboonny how about we change the "Application Errors" to "Application Troubleshooting" for consistency?  It says "Application Errors" in [the issue](https://github.com/freeCodeCamp/chapter/issues/471), but that wasn't purposely different. I think I just started out with an Errors heading and then used Troubleshooting on all the others.

**Comment by allella** [comment]
This looks good to me.  Is there anything else you wanted to add before merging?

**Comment by Sboonny** [comment]
LGTM

**Pull request merged**
