### PR TITLE
refactor: simplify updateEvent resolver

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
- refactor: simplify updateEvent using helpers
- refactor: break down updateEvent some more

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

`updateEvent` had got a bit too unwieldy, so this PR breaks it into more manageable chunks.

### CODE REVIEW

**Review by gikf — APPROVED** [review]
Oh yes, this is nice :+1:

**Comment by ojeytonwilliams** [comment]
@gikf today I discovered https://eslint.org/docs/latest/rules/complexity and I've been using it to find the most convoluted functions. It's pretty sweet!

**Comment by gikf** [comment]
@ojeytonwilliams You made me curious to check how the scores look like. I honestly thought there will be more files affected by high complexity.

**Comment by ojeytonwilliams** [comment]
Me too. Turns out we're not *terrible* on that front, which is nice. However, it's a pretty simple metric: how branched is a function? That doesn't catch anything like massive components should be broken up, unless they also have a lot of conditionals.

**Pull request merged**
