### PR TITLE
Add lint stage in CI

### PR DESCRIPTION
**Pull request by matjack1**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

I'm proposing to add a linter stage to our CI build as suggested in this comment: https://github.com/freeCodeCamp/chapter/pull/134#issuecomment-545598705

### CODE REVIEW

**Comment by vkWeb** [comment]
@matjack1 Thank you for this change. Looks good to me. 🎉

**Comment by nik-john** [comment]
@all-contributors please add @matjack1   for platform

**Comment by nik-john** [comment]
@all-contributors please add @matjack1 for platform

**Comment by nik-john** [comment]
@all-contributors please add @matjack1 for platform

**Pull request merged**
