### PR TITLE
feat: polish dashboard eventsPage's event status

### PR DESCRIPTION
**Pull request by Sboonny**
- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `main` branch of Chapter.

Update dashboard event status

Ref #1881

### CODE REVIEW

**Review by ojeytonwilliams — CHANGES_REQUESTED** [review]
By writing `Ended at: Sat, Nov 12 @ 12:30`, say, we're implying that's when the event ended. However, we only display the start date.

To make it a little more obvious, we could do something like the following. 

- Display both start and end dates. i.e `Sat, Nov 12 @ 12:30 to Sat, Nov 12 @ 12:45` (nice to have: `Sat, Nov 12 @ 12:30 to 12:45` for single day events).
- Use `Ended`, not `Ended at`
- Put the status after the date `Sat, Nov 12 @ 12:30 to 12:45, cancelled`...
- ...or separately `Status: ended`.

What do you reckon?

**Comment by ojeytonwilliams** [comment]
> Someone can always click on the event to see when it started and ended

Amazingly, they can't. The event page hasn't got this info!  I'll create an issue in a sec.

Back on topic: 

> but it's probably more important to show the end time than the start time.

Sure. The main thing is that it's obvious that it's over and when it ended.

**Comment by allella** [comment]
The home page has the same "Ending at" and you can click on the past event.  I didn't log in to check the dashboard and assumed they were on the same template.

**Comment by ojeytonwilliams** [comment]
@Sboonny don't worry about the pending checks. The next time you push a commit, they'll run.

**Review by ojeytonwilliams — APPROVED** [review]
We should find a nice way to display the end date, as Jim pointed out, but this is a step in the right direction. 

LGTM :+1:

**Comment by ojeytonwilliams** [comment]
@Sboonny the event card and dashboard's don't match (dashboard was correct, imo, so I merged this), but I left https://github.com/freeCodeCamp/chapter/issues/1881 open as a result.

**Comment by Sboonny** [comment]
have opened #1921 to make them match, you are talking about the texts `Ending at` and `Ending`, right?

**Comment by ojeytonwilliams** [comment]
Yep, I think that's what #1881 was about.

**Pull request merged**
