### PR TITLE
feat: sendgrid

### LINKED ISSUE #1232: Configure email in production
We have nodemailer set up as our email client, which works well locally, but needs additional configuration before it can work remotely.

### PR DESCRIPTION
**Pull request by naomi-lgbt**
- [X] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/main/CONTRIBUTING.md).
- [X] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [X] My pull request targets the `main` branch of Chapter.

Closes #1232 

This should allow us to use Sendgrid in a production environment while not impacting the nodemailer for development environments.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

### CODE REVIEW

**Review by ojeytonwilliams — APPROVED** [review]
LGTM :+1:

**Review by Sboonny — APPROVED** [review]
What sorcery is this, getting sendgrid review request while reading their wiki. 🧙‍♀️

**Review by Sboonny — APPROVED** [review]
LGTM 🎉, thank you for your contribution to the page! 👍. 

Edit I don't need to approve it again 🤣

**Comment by allella** [comment]
My two cents, I know fCC is "dogfooding" this, but we did have a long conversation about not adding on specific packages, and rather using secure SMTP for the eventual product.

It seems like a slippery slope, as I assume others will want all of the other packages and unless they can be dynamically enabled from the server, it may end up being a lot of bloat.

I'm not an expert on the JS stack, so feel free to share if/how supporting all the specific 3rd party service libraries would work vs using the SMTP protocol to relay through any mail service that uses SMTP (which I assume to be most / all).

**Comment by allella** [comment]
Some of the earlier threads
https://github.com/freeCodeCamp/chapter/issues/283

https://github.com/freeCodeCamp/chapter/wiki/Meeting-Notes-February-23,-2020#email-service

**Pull request merged**
