### PR TITLE
feat: the docker folder contains scripts and assets for creating and …

### PR DESCRIPTION
**Pull request by tomnoland**
…running the chapter images with mapped volumes and for general Docker maintenance

- [x] I have read [Chapter's contributing guidelines](https://github.com/freeCodeCamp/chapter/blob/master/CONTRIBUTING.md).
- [x] My pull request has a descriptive title (not a vague title like `Update README.md`).
- [x] My pull request targets the `master` branch of Chapter.

### CODE REVIEW

**Comment by allella** [comment]
@tomiiide @Zeko369 could you checkout @tomnoland 's suggestions on this one?

I'm out of my realm with no Docker experience.

**Comment by allella** [comment]
@tomnoland does the recent 'pg' Node version fix help out with the work you've been doing on Docker?

**Comment by katien** [comment]
He's using node 13 in his docker image so things should have been working for him either way, my fix was for an issue that was encountered on 14/15

**Comment by tomnoland** [comment]
Yeah, I can switch everything to Node 14 now.

**Comment by NorthDecoder** [comment]
Hi @tomnoland !  My thought was to do some testing on this request, please pardon me for being obtuse.  I am looking at https://github.com/tomnoland/chapter trying to find where the commits are for this pull request.  On this pull request page however, when I hover over the from __`tomnoland:feat/docker-mapped_volumes`__ icon at the top of the page it tells me __`This repository has been deleted`__.  It looks like you put considerable thought into the recommendation, has there been an important change?

**Comment by allella** [comment]
I think Tom started down a new thought path on #408, so perhaps that's worth a look.  I haven't been too involved in the Docker stuff. However, it does seem we'll have multiple Docker configs. For instance, SchemaSpy #453 is being used manually right now and it has a Docker option that we likely would have in a different directory than the dev or other containers.

**Comment by NorthDecoder** [comment]
As noted above this pull request in now obsolete and should be closed to avoid further discussion about code that can no longer be referenced.

**Comment by allella** [comment]
@tomnoland 

@ojeytonwilliams was looking at reorganizing the some of the directories, like /server.

I figured that may overlap with #406 and #408 and you may have ideas on where things should go. If you have any thoughts, in general, or specific to Docker, then please feel free to share with Oliver.

**Comment by allella** [comment]
https://chat.freecodecamp.org/channel/chapter?msg=QsbkFyoqcNhhoTJGB

**Comment by ojeytonwilliams** [comment]
@tomnoland I didn't realise that renaming master to main would close this, sorry!  Do you still have the code locally?

**Pull request closed without merging**
